<?=$this->form()->openTag($form);?>
    <div class="form-messages"><?= $this->formErrors; ?></div>
    <?= $this->originalFields; ?>
    <?=$this->formInput($form->get('choice_id')); ?>
    <?=$this->formInput($form->get('option_id')); ?>
    <?=$this->formInput($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?=$this->speckCatalogManagerFormRow($form->get('override_name')); ?>
        </div>
        <div class="span2">
        </div>
        <div class="span2">
        </div>
    </div>

</form>
