<div class="span2 offset1 well">
    <div class="row">
        <div class="span2">
            <?=$uomTranslated; ?>
        </div>
    </div>
    <div class="row">
        <div class="span1">
            <h5>$ <?= number_format($uom->getPrice(), 2); ?></h5>
        </div>
        <div class="span1">
            <?=$this->formInput($form->get('quantity')->setAttribute('class', 'span1')); ?>
        </div>
    </div>
    <div class="row">
        <div class="span2">
        <?=$this->formInput($form->get('submit')->setAttribute('class', 'span2 btn')); ?>
        </div>
    </div>
</div>
