<div style="row" class="span12">
    <div class="span3">
        <?= $this->formLabel($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?= $this->formLabel($form->get('quantity')); ?>
    </div>
    <div class="span2" style="align:bottom">
        &nbsp;<br/>
    </div>
</div>
<div style="row" class="span12">
    <div class="span3">
        <?= $this->formSelect($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?= $this->formInput($form->get('quantity')->setAttribute('class', 'span1')->setValue(1)); ?>
    </div>
    <div class="span2" style="align:bottom">
        <?= $this->formInput($form->get('submit')->setAttribute('class', 'btn')); ?>
    </div>
</div>
