<? if($this->itemUom) : ?>
    <!-- item uom -->
    <div class="existing">
        <span class="label">Uom</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/add.phtml', array(
                    'class' => 'uom', 'dropdown' => '1', 'selected' => $itemUom->getUom(),
                ));?>   
                <?=$this->partial('catalogmanager/partial/editform.phtml', array(
                    'form' => $forms['item-uoms'][$itemUom->getItemUomId()],
                ));?>
            </div>
            <div class="span11">
                <div class="list-wrap">
                    <div class="list-items">
                        <? if (count($this->itemUom->getAvailabilities()) > 0) : ?>
                            <? foreach($this->itemUom->getAvailabilities() as $availability) : ?>
                                <?=$this->partial('/catalogmanager/partial/product/item/item-uom/availability.phtml', array(
                                    'availability' => $availability, 'forms' => $forms,
                                ));?>
                            <? endforeach; ?>
                        <? endif; ?>
                    </div>
                    <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'availability', 'add' => '1'));?>
                    <?=$this->render('/catalogmanager/partial/product/item/item-uom/availability.phtml');?>
                </div>
            </div>
        </div>
    </div>
<? else: ?>
    <!-- new item uom -->
    <div class="hide add-new">
        <span class="label success">New Uom</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/add.phtml', array(
                    'class' => 'uom', 'dropdown' => '1',
                ));?>   
                <?=$this->partial('catalogmanager/partial/editform.phtml', array(
                    'form' => $forms['blank']['item-uom'],
                ));?>
            </div>
            <div class="span11">
                <div class="list-wrap">
                    <div class="list-items">
                    </div>
                    <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'availability', 'add' => '1'));?>
                    <?=$this->render('/catalogmanager/partial/product/item/item-uom/availability.phtml');?>
                </div>
            </div>
        </div>  
    </div>
<? endif; ?>
