<hr/>
<? if($this->itemUom) : ?>
    <!-- item uom -->
    <span class="label">ItemUom</span>
    <div class="row">
        <div class="span5">
            <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['item']['item-uoms'][$itemUom->getItemUomId()]['form']));?>
        </div>
        <div class="span11">
            <h4>Uom:</h4>
            <? if($this->itemUom->getUom()) :?>
                    <?=$this->partial('/catalogmanager/partial/product/item/item-uom/uom.phtml', array('uom' => $itemUom->getUom(), 'forms' => $forms));?>
            <? else : ?>
                    <div class="add-new">
                        <?=$this->render('/catalogmanager/partial/product/item/item-uom/uom.phtml');?>
                    </div>
            <? endif; ?>
            <h4>Availabilities:</h4>
            <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'availability'));?>
            <? if (count($this->itemUom->getAvailabilities()) > 0) : ?>
                <? foreach($this->itemUom->getAvailabilities() as $availability) : ?>
                    <?=$this->partial('/catalogmanager/partial/product/item/item-uom/availability.phtml', array(
                        'availability' => $availability,
                        'forms' => $forms,
                    ));?>
                <? endforeach; ?>
            <? endif; ?>
            <div class="add-new">
                <?=$this->render('/catalogmanager/partial/product/item/item-uom/availability.phtml');?>
            </div>
        </div>
    </div>
<? else: ?>
    <!-- new item uom -->
    <span class="label success">New ItemUom</span>
    <div class="row">
        <div class="span5">
            <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['item-uom']));?>
        </div>
        <div class="span11">
            <h4>Uom:</h4>
            <div class="add-new">
                <?=$this->render('/catalogmanager/partial/product/item/item-uom/uom.phtml');?>
            </div>

            <h4>Availabilities:</h4>
            <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'availability'));?>
            <div class="add-new">
                <?=$this->render('/catalogmanager/partial/product/item/item-uom/availability.phtml');?>
            </div>
        </div>
    </div>
<? endif; ?>
