<h1>Option<h1>
<h3>Parent Shells:</h3>
<? if (count($shell->getParentShells()) > 0) : ?>
    <ul>
        <? foreach($choice->getParentShells() as $this->shell) : ?>
            <li><?=$this->render('catalogmanage/partial/shell-icon.phtml');?></li>
        <? endforeach; ?>
    </ul>
<? else : ?>
(none)
<? endif; ?>

<h3>Choices:</h3>
<? if (count($option->getChoices()) > 0) : ?>
    <ul>
        <? foreach($choice->getChoices() as $this->choices) : ?>
            <li><?=$this->render('catalogmanage/partial/choice-icon.phtml');?></li>
        <? endforeach; ?>
    </ul>
<? else : ?>
(none)
<? endif; ?>



<h3>Selected Choice:</h3>
<? if ($option->getSelectedChoice()) : ?>
    <ul>
        <? $this->selectedChoice = $option->getSelectedChoice(); ?>
        <li><?=$this->render('catalogmanage/partial/choice-icon.phtml');?></li>
    </ul>
<? else : ?>
    Not Set
<? endif; ?>

<? die(); ?>   
