<h1>Shell<h1>
<h3>Parent Choices:</h3>
<? if (count($shell->getParentChoices()) > 0) : ?>
    <ul>
        <? foreach($shell->getParentChoices() as $this->choice) : ?>
            <li><?=$this->render('catalogmanage/partial/choice-icon.phtml');?></li>
        <? endforeach; ?>
    </ul>
<? else : ?>
(none)
<? endif; ?>



<? if($shell->getType() === 'product') : ?>
    <h3>Product:</h3>
    <? $this->product = $shell->getProduct(); ?>
    <ul>
        <li><?=$this->render('catalogmanage/partial/product-icon.phtml'); ?></li>
    </ul>
<? endif; ?>

<h3>Options:</h3>
<? if (count($shell->getOptions()) > 0) : ?>
    <ul>
        <? foreach($shell->getOptions() as $this->option) : ?>
            <li><?=$this->render('catalogmanage/partial/option-icon.phtml');?></li>
        <? endforeach; ?>
    </ul>
<? else : ?>
    No Options
<? endif; ?>

<? die(); ?>
                                                        
