<? $pdir = '/catalogmanager/partial/'; ?>

<ul class="tabs" data-tabs="tabs">
    <li class="active"><a href="#product">Product</a></li>
    <li><a href="#options">Options</a></li>
</ul>
 
<div class="pill-content">

    <div class="active boundary" id="product">

        <div class="entity-header hide"><div class="title"></div></div>
        <div class="entity-content">
        <?=$this->partial($pdir.'form/product.phtml', array('product' => $product));?><br/>

        <? if($product->isItem()) :?>
                <div class="list-wrap">
                    <div class="child-expand list-items-helper">
                        <div><span class="collapse-all ui-icon ui-icon-arrowstop-1-n ui-state-default ui-corner-all"></span></div>
                        <div><span class="expand-all ui-icon ui-icon-arrowstop-1-s ui-state-default ui-corner-all"></span></div>
                        <span class="smallcaps">&nbsp;images</span><br/>
                    </div>   
                    <div class="list-items">
                        <? if (1===2) : //($product->hasUoms()) : ?>
                            <? foreach($product->getUoms() as $productUom) : ?>
                                <?=$this->partial($pdir.'product-uom.phtml', array('productUom' => $productUom));?>
                            <? endforeach; ?>
                        <? endif; ?>
                    </div>
                    <div class="row list-items-helper">
                        <?=$this->partial($pdir.'add.phtml', array(
                            'function'        => 'import-file',
                            'name'            => 'image',
                            'className'       => 'image',
                            'parentClassName' => 'product',
                            'parentId'        => $product->getProductId(),
                        ));?>
                    </div>
                </div> 
        
                <div class="list-wrap">
                    <div class="child-expand list-items-helper">
                        <div><span class="collapse-all ui-icon ui-icon-arrowstop-1-n ui-state-default ui-corner-all"></span></div>
                        <div><span class="expand-all ui-icon ui-icon-arrowstop-1-s ui-state-default ui-corner-all"></span></div>
                        <span class="smallcaps">&nbsp;uoms</span><br/>
                    </div>   
                    <div class="list-items">
                        <? if ($product->hasUoms()) : ?>
                            <? foreach($product->getUoms() as $productUom) : ?>
                                <?=$this->partial($pdir.'product-uom.phtml', array('productUom' => $productUom));?>
                            <? endforeach; ?>
                        <? endif; ?>
                    </div>
                    <div class="row list-items-helper">
                        <?=$this->partial($pdir.'add.phtml', array(
                            'function'        => 'add-button',
                            'ClassName'       => 'productUom',
                            'newClassName'    => 'productUom',
                            'parentClassName' => 'product',
                            'parentId'        => $product->getProductId(),
                        ));?>
                    </div>
                </div>
        <? endif; ?>
        </div>

    </div>

    <div id="options" class="boundary">
        <div class="list-wrap">
            <div class="child-expand list-items-helper">
                <div><span class="collapse-all ui-icon ui-icon-arrowstop-1-n ui-state-default ui-corner-all"></span></div>
                <div><span class="expand-all ui-icon ui-icon-arrowstop-1-s ui-state-default ui-corner-all"></span></div>
            </div>
            <div class="list-items">
                <? if ($product->hasOptions()) : ?>
                    <? foreach ($product->getOptions() as $option) : ?>
                        <?=$this->partial($pdir.'option.phtml', array('option' => $option));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'add-button',
                    'newClassName'    => 'option',
                    'parentClassName' => 'product',
                    'parentId'        => $product->getProductId(),
                ));?>
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'option',
                    'className'       => 'option',
                    'parentClassName' => 'product',
                    'parentId'        => $product->getProductId()
                ));?>
            </div>
        </div> 
    </div>

</div>

<div class="hide">

    <div class="tab-pane" id="specs">
        <div class="add-new">
            add a spec
        </div>
    </div>

    <div class="tab-pane" id="parent-choices">
            <? if (count($product->getParentChoices()) > 0) : ?>
                <?=$this->partial($pdir.'entity-list.phtml', array('paginator' => $parentChoicesPaginator)); ?>       
            <? endif; ?>  
    </div>

</div>
