<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
</head>
<body>
<style>
.clear{clear:both}
*{margin:0; padding:0}
div.entity{margin:10px; border:1px solid #999999; padding:10px; width:550px;}
    div.entities{float:right;}
        input.add_search{width:50px;}
        .icon{border:1px solid #999999; padding:5px; display:block; width:200px;}
        .shell{background:#cccccc}
        .product{background:#bbddff}
        .option{background:#ffbb99}
        .choice{background:#ff9999}
        .product_uom{background:#ffffbb}
        .productUom{background:#ffffbb}
        .availability{background:#bbffbb}
        .company{background:#ffccff}
        .uom{background:#ffffff}
        .add{background:#f7f7f7;}
    div.editform{float:left; width:300px; min-height:200px; background:#eeeeee; border:1px solid #999999; padding:10px;}
.right{float:right}
</style>
<?php echo $this->raw('content'); ?>

</body>
<script>
$('.newDropdown').change(function() {
    var selected = $(this).find("option:selected");
    if(selected.hasClass('selection')){
        var parts = selected.val().split(' ');
        location.href=parts[1]+"?constructor="+parts[0];
    }
});
</script>
</html>
