<? if(isset($nolayout)) : ?>
    <? echo $this->raw('content'); ?>
<? else : ?>
    <?php echo $this->doctype() ?>

    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headTitle() ?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" href="/bootstrap.min.css">
		<link type="text/css" href="/css/smoothness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />	
        <script src="/jquery.min.js"></script> 
		<script src="/js/jquery-ui-1.8.16.custom.min.js"></script>
        <script src="/bootstrap-dropdown.js"></script>
        <script src="/bootstrap-modal.js"></script> 
        <script src="/bootstrap-alerts.js"></script> 
        <script src="/bootstrap-twipsy.js"></script> 
        <script src="/bootstrap-popover.js"></script> 
        <script src="/bootstrap-scrollspy.js"></script> 
        <script src="/bootstrap-tabs.js"></script> 
        <script src="/bootstrap-buttons.js"></script>     
        <script src="/js/catalogmanager.js"></script>
    </head>
    <style>
        body{
            
            margin:40px; 
            background:#ffffff
        }
        .add-new{
            /* border-top:1px solid #55ff55; border-bottom:1px solid #eeeeee; */
            margin-bottom:4px; 
            padding: 5px 0 5px 0;
        }
        .existing{
            /* border-top:1px solid #cccccc; border-bottom:1px solid #eeeeee; */
            padding: 5px 0 5px 0; 
            margin-bottom:4px
        }
        .add-element{
            padding:5px 0 5px 0;
        }
        .container-wrap{
            width:940px; 
            background:#ffffff; 
            padding:10px; 
            margin:0 auto; margin-bottom:250px; 
            border:1px solid #cccccc; 
            -webkit-border-radius:0 0 4px 4px;
            -moz-border-radius:0 0 4px 4px;
            border-radius:0 0 4px 4px;
        }
        .editform input{
            width:140px;
        }
        .sortable-placeholder{ height:100px; border:1px solid #f5f5f5; background:#fafafa; padding: 5px }
        .sort-handle{border:1px solid #555555; cursor:move;}
        .remover{cursor:hand; cursor:pointer;}
        .half-pad{margin-left:40px;}
        .quarter-pad{margin-left:20px; margin-bottom:20px;}
        .whitebg{
            /* border-left:1px solid #dddddd; */
            background:#ffffff;
        }
        .contrastbg{
            /* border-left:1px solid #dddddd; */
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#eeeeee', endColorstr='#fff'); /* for IE */
background: -webkit-gradient(linear, left top, right top, from(#eef), to(#fff)); /* for webkit browsers */
background: -moz-linear-gradient(left,  #eee,  #fff); /* for firefox 3.6+ */ 

        }
        .collapsed{border:2px solid #000000;}
        .label{margin-left:5px; border:1px solid #777777;}
        .entity-header{height:20px;}
        .entity-header span.ui-icon{margin-top:1px; margin-left:5px;}
        .entity-header div{float:left;}
        .deported{
            border-bottom:10px solid #ff0000; 
            border-top:1px solid #ff0000;
            background:#ff9999; 
            padding: 5px 0 5px 0; 
            margin-bottom:4px
        }
        .imported{
            border-bottom:10px solid #0000ff; 
            border-top:1px solid #0000ff;
            background:#9999ff; 
            padding: 5px 0 5px 0; 
            margin-bottom:4px
        }
    </style>

    <body>

        <div class="topbar-wrapper" style="z-index: 5;">
            <div class="topbar" data-dropdown="dropdown">
                <div class="topbar-inner">
                   <div class="container">

                        <h3><a href="/catalogmanager">CatalogManager</a></h3>

                        <ul class="nav">
                            <li class="active"><a href="/catalogmanager">Home</a></li>
                            <li><a href="#"></a></li>
                            <li><a href="#"></a></li>
                            <li><a href="#"></a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle">New Product</a>
                                <ul class="dropdown-menu">
                                    <li><a href="/catalogmanager/product?constructor=product" 
                                           title="Single product with an item number">Product (Item)</a>
                                    </li>
                                    <li><a href="/catalogmanager/product?constructor=shell" 
                                           title="Group similar products together to be displayed as one">Product Group</a>
                                    </li>
                                    <li><a href="/catalogmanager/product?constructor=builder" 
                                           title="Intended for a single product with options that help compose the item number">Product Builder</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li><a href="#">Another link</a></li>
                                </ul>
                            </li>
                        </ul>

                        <form class="pull-left" action="">
                            <input class="span3" type="text" placeholder="Search">
                        </form>

                        <ul class="nav secondary-nav">
                            <? if($this->edpUser()) : ?>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle">
                                        <? if(isset($session)):?><strong>(<?=count($session);?>)</strong><? endif; ?>
                                        <?=$this->edpUser()->getDisplayName();?>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li> asdf </li>
                                        <li class="divider"></li>
                                        <li>
                                            <a href="/user/logout">
                                                Logout
                                            </a>
                                        </li> 
                                    </ul>
                                </li>  
                            <? endif; ?>
                        </ul>

                    </div>
                </div><!-- /topbar-inner -->
            </div><!-- /topbar -->
        </div>
        
        <? if (isset($messages)) : ?>
            <? foreach($messages as $this->message) : ?>
                <?=$this->render('/catalogmanager/partial/alert-message.phtml'); ?>
            <? endforeach; ?>
        <? endif; ?>

        <div class="content"> 
            <div class="row"> 
                <div class="span16"> 
                    <?php echo $this->raw('content'); ?>
               </div> 
            </div> 
        </div> 

        <!-- Modal -->
        <div class="modal hide fade in" id="modal-box" >
            <div class="modal-header">
                <a class="close" href="#">×</a>
                <h3></h3>
            </div>
            <div class="modal-body">
                <p>no results…</p>
            </div>
            <div class="modal-footer">
                <a class="btn primary" href="#">Primary</a>
                <a class="btn secondary" href="#">Secondary</a>
            </div>
        </div>

    </body>
    </html>
<? endif; ?>
