<div class="availability entity">
    <h1>Availability</h1>
    <div class="entities">
        <h3>Parent Product Uom:</h3>
        <? if ($availability->getParentProductUom()) : ?>
            <ul>
                <? $this->productUom = $availability->getParentProductUom(); ?>
                <li class="product_uom icon"><?=$this->render('catalogmanage/partial/product-uom-icon.phtml');?></li>
            </ul>
        <? else : ?>
            <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? endif; ?>

        <h3>Distributor:</h3>
        <? if ($availability->getDistributor()) : ?>
            <ul>
                <? $this->company = $availability->getDistributor(); ?>
                <li class="company icon"><?=$this->render('catalogmanage/partial/company-icon.phtml');?></li>
            </ul>
        <? else : ?>
            <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? endif; ?>  
    </div>
    <?=$this->render('catalogmanage/partial/editform.phtml');?>
    <div class="clear"></div>
</div>
