<div class="choice entity">
    <h1>Choice</h1>
    <div class="entities">
        <h3>Parent Options:</h3>
        <? if (count($choice->getParentOptions()) > 0) : ?>
            <ul>
                <? foreach($choice->getParentOptions() as $this->option) : ?>
                    <li class="option icon"><?=$this->render('catalogmanage/partial/option-icon.phtml');?></li>
                <? endforeach; ?>
            </ul>
        <? else : ?>
            <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? endif; ?>

        <h3>Shell:</h3>
        <? if ($choice->getShell()) : ?>
            <ul>
                <? $this->shell = $choice->getShell(); ?>
                <li class="shell icon"><?=$this->render('catalogmanage/partial/shell-icon.phtml');?></li>
            </ul>
        <? else : ?>
            <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? endif; ?>
    </div> 
    <?=$this->render('catalogmanage/partial/editform.phtml');?>
    <div class="clear"></div>   
</div>
