<div class="option entity">
    <h1>Option</h1>
    <div class="entities">
        <h3>Parent Shells:</h3>
        <? $this->class = 'shell'; ?>
        <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? if (count($option->getParentShells()) > 0) : ?>
            <ul>
                <? foreach($option->getParentShells() as $this->shell) : ?>
                    <li class="shell icon"><?=$this->render('catalogmanage/partial/shell-icon.phtml');?></li>
                <? endforeach; ?>
            </ul>
        <? else : ?>
        (none)
        <? endif; ?>

        <h3>Selected Choice:</h3>
        <? if ($option->getSelectedChoice()) : ?>
            <ul>
                <? $this->choice = $option->getSelectedChoice(); ?>
                <li class="choice icon"><?=$this->render('catalogmanage/partial/choice-icon.phtml');?></li>
            </ul>
        <? else : ?>
            <? $this->class = 'choice'; ?>
            <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? endif; ?>

        <h3>Choices:</h3>
        <? $this->class = 'choice'; ?>
        <?=$this->render('catalogmanage/partial/add.phtml');?>
        <? if (count($option->getChoices()) > 0) : ?>
            <ul>
                <? foreach($option->getChoices() as $this->choice) : ?>
                    <li class="choice icon"><?=$this->render('catalogmanage/partial/choice-icon.phtml');?></li>
                <? endforeach; ?>
            </ul>
        <? else : ?>
        (none)
        <? endif; ?>
    </div>
    <?=$this->render('catalogmanage/partial/editform.phtml');?>
    <div class="clear"></div>    
</div>
