<div class="container">
    <div class="row">
        <div class="span3 bs-docs-sidebar" style="border:1px solid black">
            <ul class="nav nav-list bs-docs-sidenav">
              <? foreach($categories as $category) : ?>
                <li>
                    <a href="/category/<?=$category->getCategoryId(); ?>"><?=$category;?></a>
                </li>
              <? endforeach; ?>
            </ul>
        </div>
    </div>
</div>
