<?
    $pdir = '/speck-catalog/catalog/partial/';
?>

<? foreach ($option->getChoices() as $choice): ?>
    <?
        $optionId = $option->getOptionId();
        $choiceId = $choice->getChoiceId();
    ?>
    <input name="product_branch[<?=$optionId;?>]" value="<?=$choiceId;?>" type="radio">
        &nbsp;<?=$choice; ?>
    </input>
    <? if($choice->has('options')) : ?>
        <? foreach($choice->getOptions() as $option) : ?>
            <br/><?=$this->partial($pdir . 'option.phtml', array('option' => $option)); ?>
        <? endforeach; ?>
    <? else: ?>
        <br/>
    <? endif; ?>
<? endforeach; ?>
