<? $pdir = '/speck-catalog/catalog/partial/'; ?>
<? foreach ($option->getChoices() as $choice): ?>
    <input name="product_branch[<?=$option->getOptionId();?>][<?=$choice->getChoiceId(); ?>]" value="<?=$choice->getChoiceId();?>" type="radio">&nbsp;<?=$choice->__toString();?>
    <? if($choice->has('options')) : ?>
        <? foreach($choice->getOptions() as $option) : ?>
            <br/><?=$this->partial($pdir . 'option.phtml', array('option' => $option)); ?>
        <? endforeach; ?>
    <? else: ?>
        <br/>
    <? endif; ?>
<? endforeach; ?>
