<? $pdir = '/catalogmanager/partial/'; ?>
    <div class="existing contrastbg boundary">
    <div class="entity-header">
        <div><span class="ui-icon ui-icon-triangle-1-s collapser"></span></div>
        <div class="remover"><div class="hide"><span class="ui-icon ui-icon-trash"></span></div></div>
        <div class="title sort-handle collapser">&nbsp;<?=$productUom;?></div>
    </div>  
        <div class="entity-content">
            <div class="row">
                <div class="span5">
                    <?=$this->partial($pdir.'form/product-uom.phtml', array('productUom' => $productUom));?>
                </div>
                <div class="span10">
                    <div class="list-wrap">
                        <div class="child-expand list-items-helper">
                        <div><span class="collapse-all ui-icon ui-icon-arrowstop-1-n ui-state-active ui-corner-all"></span></div>
                        <div><span class="expand-all ui-icon ui-icon-arrowstop-1-s ui-state-active ui-corner-all"></span></div>
                            <span class="smallcaps">&nbsp;availabilities</span><br/>
                        </div>  
                        <div class="list-items">
                            <? if ($productUom->hasAvailabilities()) : ?>
                                <? foreach($productUom->getAvailabilities() as $availability) : ?>
                                    <?=$this->partial($pdir.'availability.phtml', array('availability' => $availability));?>
                                <? endforeach; ?>
                            <? endif; ?>
                        </div>
                        <div class="row list-items-helper">
                            <?=$this->partial($pdir.'add.phtml', array(
                                'function'        => 'add-button',
                                'newClassName'    => 'availability',
                                'parentClassName' => 'productUom',
                                'parentId'        => $productUom->getProductUomId(),
                            ));?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

