<?= $this->speckCatalogManagerSideNav(); ?>
<div class="offset3 span9">
    <div class="list-wrap half-pad">
        <div class="child-expand list-items-helper">
            <div class="collapse-all"><i class="icon-arrow-up"></i></div>
            <div class="expand-all"><i class="icon-arrow-down"></i></div>
            <span class="smallcaps">&nbsp;categories</span><br/>
        </div>
        <div class="list-items">
            <?=$this->speckCatalogRenderChildren('category', $categories); ?>
        </div>
        <div class="row list-items-helper">
            <?=$this->speckCatalogAdderHelper()->addNew('category', 'category', array('category_id' => null)); ?>
        </div>
    </div>
</div>
