<div class="row">
    <?= $this->speckCatalogManagerSideNav(); ?>

    <div class="span7">
        <h4>Site Tree</h4>
        <select id="site-select" class="span4">
            <option value=''>-- Choose a Site --</option>
            <? foreach($sites as $site) : ?>
                <option value="<?=$site->getSiteId();?>"><?=$site->getName();?></option>
            <? endforeach; ?>
        </select>
        <div id="option-tree" style="max-height:300px; height:300px; overflow-y:scroll">select a site from the above dropdown</div>
    </div>
    <div class="span3 tabbable">

        <ul class="nav nav-tabs">
            <li class="active"><a href="#products" data-toggle="tab">Find Products</a></li>
            <li><a href="#categories" data-toggle="tab">Find Categories</a></li>
        </ul>

        <div class="tab-content">
            <div id="products" class="tab-pane">
                <input type="text" class="span3" name="search-product">
                <div class="well" id="product-results" style="max-height:300px; height:300px; overflow-y:scroll">
                    search for products above
                </div>
            </div>
            <div id="categories" class="tab-pane">
                <input type="text" class="span3" name="search-category">
                <div class="well" id="category-results" style="max-height:300px; height:300px; overflow-y:scroll">
                    search for products above
                </div>
            </div>
        </div><!-- /tab-content -->

    </div><!-- /tabbable -->
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('select#site-select').live('change', function(){
            getSiteTree();
        })
        function getSiteTree(){
            if($('select#site-select').val()){
                $.post('/catalogmanager/category-tree-preview/' + $('select#site-select').val(), null, function(html){
                    $('div#option-tree').html(html);
                })
            } else {
                $('div#option-tree').html('');
            }
        }
    })
</script>
