<? $pdir = '/catalog-manager/partial/'; ?>
<div class="list-wrap half-pad">
    <div class="child-expand list-items-helper">
        <div class="collapse-all"><i class="icon-arrow-up"></i></div>
        <div class="expand-all"><i class="icon-arrow-down"></i></div>
        <span class="smallcaps">&nbsp;companies</span>
    </div>
    <div class="list-items">
        <? foreach($companies as $company) : ?>
            <?=$this->partial($pdir.'company.phtml', array('company' => $company, 'contrastbg' => 'contrastbg'));?>
        <? endforeach; ?>
    </div>
    <div class="row list-items-helper">
        <?=$this->partial($pdir.'add.phtml', array(
            'function' => 'add-button',
            'newClassName' => 'company',
            'parentClassName' => 'company',
            'parentId' => 0,
            'partialName' => 'company',
        ));?>
        <?=$this->partial($pdir.'add.phtml', array(
            'function'  => 'import-search',
            'searchClassName' => 'company',
            'className' => 'company',
            'parentClassName' => 'company',
            'parentId' => 0,
            'partialName' => 'company',
        ));?>
    </div>
</div>

<?=$this->render($pdir.'modal.phtml'); ?>
