<? $pdir = '/catalog/catalog-manager/partial/'; ?>
<div class="list-wrap half-pad">
    <div class="child-expand list-items-helper">
        <div class="collapse-all"><i class="icon-arrow-up"></i></div>
        <div class="expand-all"><i class="icon-arrow-down"></i></div>
        <span class="smallcaps">&nbsp;companies</span><br/>
    </div>
    <div class="list-items">
        <?=$this->speckCatalogRenderChildren($companies); ?>
    </div>
    <div class="row list-items-helper">
        <?=$this->speckCatalogAdderHelper('addButton', 'company'); ?>
    </div>
</div>








<?=$this->render($pdir.'modal.phtml'); ?>
