<?
foreach($products as $product){
    echo '<a href="/catalogmanager/product/' . $product->getProductId() . '">' . $product->getProductTypeId() . ' - ' .  $product . ' </a><br/>';
}
?>
    <hr>
    <? $p = $page-1; $tag = '<a href="/catalogmanager/products/' . $p . '">'; ?>
    <? if ($p > 1) echo $tag; ?>
previous
    <? if ($p > 1) echo "</a>"; ?>
||
    <? $fp = $page+1; ?><a href="/catalogmanager/products/<?=$fp;?>">next</a>
