<? $pdir = '/catalog/catalog-manager/partial/'; ?>
<? $formHelper = $this->speckCatalogForm($product, 'product'); ?>
<? $parentKeyFields = $formHelper->getKeyFields(); ?>

<a href="/<?=$product->getProductId();?>">View this product</a><br/><br/>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product" data-toggle="tab">Product</a></li>
        <li><a href="#options" data-toggle="tab">Options</a></li>
        <li><a href="#specs" data-toggle="tab">Specs</a></li>
        <li><a href="#documents" data-toggle="tab">Documents</a></li>
        <li><a href="#images" data-toggle="tab">Images</a></li>
    </ul>

    <div class="tab-content">

        <?= $this->render($pdir . 'product'); ?>

        <div id="options" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>
                </div>
                <div class="list-items" type="option" parent="product">
                    <?= $this->speckCatalogRenderChildren('option', $product->getOptions()); ?>
                </div>
                <div class="row list-items-helper">
                    <?= $this->speckCatalogAdderHelper()->addNew('option', 'product', $parentKeyFields); ?>
                </div>
            </div>
        </div>

        <div id="specs" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items">
                    <?= $this->speckCatalogRenderChildren('spec', $product->getSpecs()); ?>
                </div>
                <div class="row list-items-helper">
                    <?= $this->speckCatalogAdderHelper()->addNew('spec', 'product', $parentKeyFields); ?>
                </div>
            </div>
        </div>

        <div id="documents" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="document" parent="product">
                    <?= $this->speckCatalogRenderChildren('document', $product->getDocuments()); ?>
                </div>
                <div class="row list-items-helper">
                    <?= $this->speckCatalogProductDocumentUploader($parentKeyFields); ?>
                </div>
            </div>
        </div>

        <div id="images" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="image" parent="product">
                    <?=$this->speckCatalogRenderChildren('product_image', $product->getImages()); ?>
                </div>
                <div class="row list-items-helper">
                    <div class="span5">
                        Upload Image
                        <?= $this->speckCatalogProductImageUploader($parentKeyFields); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/tabbable-->

<?=$this->render($pdir.'modal.phtml'); ?>
