<? $pdir = '/catalog/catalog-manager/partial/'; ?>

<a href="/<?=$product->getProductId();?>">View this product</a><br/><br/>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product" data-toggle="tab">Product</a></li>
        <li><a href="#options" data-toggle="tab">Options</a></li>
        <li><a href="#specs" data-toggle="tab">Specs</a></li>
        <li><a href="#documents" data-toggle="tab">Documents</a></li>
        <li><a href="#images" data-toggle="tab">Images</a></li>
    </ul>

    <div class="tab-content">

        <div class="active boundary tab-pane" id="product">

            <div class="entity-header hide"><div class="title"></div></div>

            <div class="entity-content">

                <?=$this->speckCatalogRenderForm($product);?>

                <? if($product->isItem()) :?>
                    <div class="list-wrap">
                        <div class="child-expand list-items-helper">
                            <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                            <div class="expand-all"><i class="icon-arrow-down"></i></div>
                            <span class="smallcaps">&nbsp;uoms</span><br/>
                        </div>
                        <div class="list-items">
                            <?=$this->speckCatalogRenderChildren($product->getUoms()); ?>
                        </div>
                        <div class="row list-items-helper">
                            <?=$this->speckCatalogAdderHelper('addButton', 'productUom', $product); ?>
                        </div>
                    </div>
                <? endif; ?>

            </div>

        </div>

        <div id="options" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>
                </div>
                <div class="list-items" type="option" parent="product">
                    <?=$this->speckCatalogRenderChildren($product->getOptions()); ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->speckCatalogAdderHelper('addButton', 'option', $product); ?>
                    <?=$this->speckCatalogAdderHelper('importSearch', 'option', $product); ?>
                </div>
            </div>
        </div>

        <div id="specs" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items">
                    <?=$this->speckCatalogRenderChildren($product->getSpecs()); ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->speckCatalogAdderHelper('addButton', 'spec', $product); ?>
                </div>
            </div>
        </div>

        <div id="documents" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="document" parent="product">
                    <?=$this->speckCatalogRenderChildren($product->getDocuments()); ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->speckCatalogAdderHelper('addButton', 'document', $product); ?>
                    <?=$this->speckCatalogAdderHelper('importSearch', 'document', $product); ?>
                </div>
            </div>
        </div>

        <div id="images" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="list-items" type="image" parent="product">
                    <?=$this->speckCatalogRenderChildren($product->getImages()); ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->speckCatalogAdderHelper('addButton', 'image', $product); ?>
                    <?=$this->speckCatalogAdderHelper('importSearch', 'image', $product); ?>
                </div>
            </div>
        </div>
    </div>
</div><!--/tabbable-->

<?=$this->render($pdir.'modal.phtml'); ?>
