<? if(is_array($message)) : ?>
  <div class="alert-message <?=$message['type'];?>">
    <a class="close" href="#">×</a>
    <p>
        <? if(isset($message['status'])) : ?><strong><?=$message['status'];?></strong><? endif; ?>
        <? if(isset($message['message'])) : ?><?=$message['message'];?><? endif; ?>
        <? if(isset($message['url'])) : ?><a href="<?=$message['url'];?>"><?=$message['url'];?></a><? endif; ?>
    </p>
  </div>
<? else : ?>
  <div class="alert-message">
    <a class="close" href="#">×</a>
    <p><?=$message;?></p>
  </div>  
<? endif; ?>
