<? $pdir = '/catalog-manager/partial/'; ?>
<div class="boundary whitebg">
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down initialCollapse"></i></div>
        <div class="remover"><div class="hide"><span class="icon-trash"></span></div></div>
        <div class="title sort-handle collapser">&nbsp; <?=$availability;?></div>
    </div>
    <div class="entity-content">   
            <?=$this->partial($pdir.'form/availability.phtml', array('availability' => $availability));?>
    </div>
</div>
