<? $pdir = '/catalog-manager/partial/'; ?>
<div class="choice whitebg boundary <?=$contrastbg;?>">
    <? if(isset($contrastbg) && $contrastbg === 'contrastbg'){$contrastbg = '';}else{$contrastbg = 'contrastbg';} ?>
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down initialCollapse"></i></div>
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <? if ($category->hasCategories()) : ?>
            <div><span class="icon-list" title="has more categories"></span></div>
        <? endif; ?>
        <div class="title sort-handle collapser">&nbsp; <?=$category;?></div>
    </div>   
    <div class="entity-content">  
        <?=$this->partial($pdir.'form/category.phtml', array('category' => $category));?>
        <div class="list-wrap half-pad">
            <div class="child-expand list-items-helper">
            <div class="collapse-all"><i class="icon-arrow-up"></i></div>
            <div class="expand-all"><i class="icon-arrow-down"></i></div>    
                <span class="smallcaps">&nbsp;categories</span><br/>
            </div>  
            <div class="list-items">
                <? if ($category->hasCategories()) : ?>
                    <? foreach($category->getCategories() as $childCategory) : ?>
                        <?=$this->partial($pdir.'category.phtml', array('category' => $childCategory, 'contrastbg' => $contrastbg));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function' => 'add-button', 
                    'newClassName' => 'category',
                    'parentClassName' => 'category',
                    'parentId' => $category->getCategoryId(),
                    'partialName' => 'category',     
                ));?>
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'  => 'import-search', 
                    'searchClassName' => 'category',
                    'className' => 'category',
                    'parentClassName' => 'category',
                    'parentId' => $category->getCategoryId(),     
                    'partialName' => 'category',     
                ));?>
            </div>             
        </div>  
        <div class="list-wrap half-pad">
            <div class="child-expand list-items-helper">
                <span class="smallcaps">&nbsp;products</span><br/>
            </div>  
            <div class="list-items">
                <? if ($category->hasProducts()) : ?>
                    <? foreach($category->getProducts() as $product) : ?>
                        <?=$this->partial($pdir.'product.phtml', array('product' => $product));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'  => 'import-search', 
                    'searchClassName' => 'product',
                    'className' => 'product',
                    'parentClassName' => 'category',
                    'parentId' => $category->getCategoryId(),     
                    'partialName' => 'product',     
                ));?>
            </div>             
        </div>  
    </div>
</div> 
