<? $pdir = '/catalog-manager/partial/'; ?>

<div class="boundary contrastbg" id="<?=$company->getRecordId();?>">
    <div class="entity-header">
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-file"></i></div>
        <div class="title sort-handle">&nbsp; <?=$company;?></div>
    </div>
    <div class="entity-content initialcol">
        <?=$this->partial($pdir.'form/company.phtml', array('company' => $company));?>
    </div>
</div>
