<? $pdir = '/catalog-manager/partial/'; ?>

<div class="boundary contrastbg">
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down initialCollapse"></i></div>
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-file"></i></div>
        <div class="title sort-handle collapser">&nbsp; <?=$image;?></div>
    </div>
    <div class="entity-content initialcol">
        <?=$this->partial($pdir.'form/image.phtml', array('image' => $image));?>
    </div>   
</div>
