<? $pdir = '/catalog-manager/partial/'; ?>

<div class="boundary contrastbg" id="<?=$image->getLinkerId();?>" >
    <div class="entity-header">
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-picture"></i></div>
        <div class="title sort-handle">&nbsp; <?=$image;?></div>
    </div>
    <div class="entity-content initialcol">
        <?=$this->partial($pdir.'form/image.phtml', array('image' => $image));?>
    </div>   
</div>
