<? $pdir = '/catalog-manager/partial/'; ?>
<div id="<?=$option->getLinkerId();?>" class="option contrastbg boundary">
    
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down"></i></div>
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <? if(1===1 || $option->isShared()) : ?>
            <? $count = count($option->getParentProducts()); ?>
            <div><i class="icon-eye-open" title="This option is shared <?=$count;?> times"></i></div>
        <? endif; ?>  
        <div class="title sort-handle collapser">&nbsp; <?=$option;?></div>
    </div>

    <div class="entity-content">   
        <?=$this->partial($pdir.'form/option.phtml', array('option' => $option));?>
        <div class="list-wrap">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;images</span>
            </div>   
            <div class="list-items" type="image" parent="product">
                <? if ($option->hasImages()) : ?>
                    <? foreach ($option->getImages() as $image) : ?>
                        <?=$this->partial(
                            $pdir.'image.phtml', 
                            array('image' => $image, 'bg' => 'whitebg', 'collapse' => true)
                        );?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'add-button',
                    'newClassName'    => 'image',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getRecordId(),
                    'partialName'     => 'image',
                ));?>
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'image',
                    'className'       => 'image',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getRecordId(),
                    'partialName'     => 'image',
                ));?>
            </div>
        </div> 

        <div class="list-wrap half-pad">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;choices</span>
            </div>
            <div class="list-items" type="choice" parent="option">
                <? if ($option->hasChoices()) : ?>
                    <? foreach($option->getChoices() as $choice) : ?>
                        <?=$this->partial($pdir.'choice.phtml', array('choice' => $choice));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'product',
                    'childClassName'  => 'product',
                    'newClassName'    => 'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getRecordId(),
                    'partialName'     => 'choice',
                ));?>    
                <?=$this->partial($pdir.'add.phtml', array(
                    'function' => 'add-button',
                    'newClassName'=>'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getRecordId(),
                    'partialName'     => 'choice',
                ));?>
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'choice',
                    'className'       => 'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getRecordId(),
                    'partialName'     => 'choice',
                ));?>    
            </div>
        </div>
    </div>

</div>
