<? $pdir = '/catalog-manager/partial/'; ?>
<!-- option -->
<div class="option contrastbg boundary">

    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down"></i></div>
        <? if(1===1 || $option->isShared()) : ?>
            <div><i class="icon-eye-open" title="This option is shared amongst <?=count($option->getParentProducts());?> products."></i></div>
        <? endif; ?>  
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div class="title sort-handle collapser">&nbsp; <?=$option;?></div>
    </div>

    <div class="entity-content">   
    <?=$this->partial($pdir.'form/option.phtml', array('option' => $option));?>
        <div class="list-wrap half-pad">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;choices</span>
            </div>
            <div class="list-items">
                <? if ($option->hasChoices()) : ?>
                    <? foreach($option->getChoices() as $choice) : ?>
                        <?=$this->partial($pdir.'choice.phtml', array('choice' => $choice));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'product',
                    'childClassName'  => 'product',
                    'newClassName'    => 'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getOptionId(),
                ));?>    
                <?=$this->partial($pdir.'add.phtml', array(
                    'function' => 'add-button',
                    'newClassName'=>'choice',
                    'parentClassName' => 'option',
                    'parentId' => $option->getOptionId(),
                ));?>
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'choice',
                    'className'       => 'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $option->getOptionId(),
                ));?>    
            </div>
        </div>
    </div>

</div>
