<?php if ($this->pageCount): ?>
<div class="pagination">
    <ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <li class="prev"><a href="#">← Previous</a></li`>
<?php else: ?>
    <li class="prev disabled"><a href="#">← Previous</a></li`>
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li><a href="#"><?=$page;?></a></li>
  <?php else: ?>
    <li class="active"><a href="#"><?=$page;?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <li class="next"><a href="#">Next →</a></li>
<?php else: ?>
    <li class="next disabled"><a href="#">Next →</a></li>
<?php endif; ?>
    </ul>

</div>
<?php endif; ?>




<? /*

<div class="pagination">
    <ul>
        <li class="prev disabled"><a href="#">← Previous</a></li`>
        
        <li class="active"><a href="#">1</a></li>

                <li><a href="#"><?=$i;?></a></li>


            <li class="next"><a href="#">Next →</a></li>
        <? else : ?>

            <li class="next disabled"><a href="#">Next →</a></li>
        <? endif; ?>
    </ul>
</div>
 */ 
?>

