<? $pdir = '/catalog-manager/partial/'; ?>

<div class="boundary contrastbg2">
    <div class="entity-header">
        <div><span class="label modal-edit-trigger entity-title">Product</span></div>
        <div> 
            &nbsp; <?=$product; ?>
            <?=$product->getItemNumber(); ?>
            <? foreach($product->getUoms() as $uom) : ?>(<?=$uom;?>)<? endforeach;?>
        </div>
    </div>
</div>
