<strong><?=$option; ?><?=($option->getRequired() ? '*' : ''); ?>:</strong>
<? if($option->has('instruction')):?><br/>&nbsp;&nbsp;&nbsp;(<?=$option->getInstruction();?>)<? endif; ?>
<? $listType = $option->getListType(); ?>
<? $choices = $option->getChoices(); ?>
<? if('radio' === $listType): ?>
    <?=$this->partial('catalog/partial/product/option/radio.phtml', array('option' => $option)); ?>
<? endif; ?>
<? if('checkbox' === $listType): ?>
    <?=$this->partial('catalog/partial/product/option/checkbox.phtml', array('option' => $option)); ?>
<? endif; ?>
<? if('dropdown' === $listType): ?>
    <?=$this->partial('catalog/partial/product/option/select.phtml', array('option' => $option)); ?>
<? endif; ?>
<hr/>
