<? if(isset($option)) : ?>
<div class="existing">
    <!-- option -->
    <span class="label">Option</span>
    <? $parentOptionCount = count($option->getParentProducts()); ?>
    <? if($parentOptionCount > 1) : ?>
        <span class="label warning" title="This option is currently shared amongst <?=$parentOptionCount;?> products.">Shared</span>
    <? endif; ?>   
    <div class="row">
        <div class="span5">
            <?=$this->render('catalogmanager/partial/editform.phtml', array(
                'form' => $forms['options'][$option->getOptionId()]['form'],
            ));?>
        </div>
        <div class="span11 parent">
            <h4>Choices:</h4>
            <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'choice', 'add' => 1));?>
            <?=$this->render('/catalogmanager/partial/product/option/choice.phtml');?>
            <? if (count($option->getChoices()) > 0) : ?>
                <? foreach($option->getChoices() as $choice) : ?>
                    <?=$this->partial('/catalogmanager/partial/product/option/choice.phtml', array(
                        'choice' => $choice, 'forms' => $forms,
                    ));?>
                <? endforeach; ?>
            <? endif; ?>
        </div>
    </div>
</div>
<? else: ?>
<div class="hide add-new">
        <!-- new option -->
        <span class="label success">New Option</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['option-radio']));?>
            </div>
            <div class="span11 parent">
                <h4>Choices:</h4>
                <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'choice', 'add' => 1));?>
                <?=$this->render('/catalogmanager/partial/product/option/choice.phtml');?>
            </div>
        </div>
</div>
<? endif; ?>

