<? foreach ($option->getChoices() as $choice): ?>
    <input name="option-<?=$option->getRecordId();?>" value="choice-<?=$choice->getRecordId();?>" type="radio">&nbsp;<?=$choice->__toString();?>
    <? if($choice->has('options')) : ?>
        <? foreach($choice->getOptions() as $option) : ?>
            <br/><?=$this->partial('catalog/partial/option.phtml', array('option' => $option)); ?>
        <? endforeach; ?>
    <? else: ?>
        <br/>
    <? endif; ?>
<? endforeach; ?>
