<? if(isset($choice)) : ?>
<div class="existing">
    <span class="label">Choice</span>
    <div class="row">
        <div class="span5">
            <? $this->choiceId = $choice->getChoiceId();?>
            <? $this->form = $this->forms['options'][$this->optionId]['choices'][$this->choiceId]['form']; ?>
            <?=$this->render('catalogmanager/partial/editform.phtml');?>  
        </div>
        <div class="span6">
            <h4>Product:</h4>
            <? if ($choice->getProduct()) : ?>
                <?=$this->partial('/catalogmanager/partial/product/option/choice/product.phtml', array(
                    'product' => $choice->getProduct(),
                ));?>
            <? else : ?>
                <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'product', 'search' => 1));?>
            <? endif; ?>
        </div>
    </div>
</div>
<? else : ?>
<div class="add-new hide">
    <span class="label success">New Choice</span>
    <div class="row">
        <div class="span5">
            <? $this->form = $forms['blank']['choice']; ?>
            <?=$this->render('catalogmanager/partial/editform.phtml');?>  
        </div>
        <div class="span6">
            <h4>Product:</h4>
                <?=$this->partial('/catalogmanager/partial/add.phtml', array('class' => 'product', 'search' => 1));?>
        </div>
    </div>
</div>
<? endif; ?>
