<?php
    $pdir = '/speck-catalog/product/';
?>
<?=$this->configureBuy($product);?>
<h2><?=$product->getName();?></h2>

<form id="configure-buy" method="POST" action="/cart/add-product">
<input type="hidden" name="product_id" value="<?=$product->getProductId();?>"/>

<div class="row">
    <div class="span3 bordered-table">
        <? if($product->has('image')): ?>
            <? $image = $product->getImage(); ?>
            <img src="<?=$this->speckCatalogImage()->product($image);?>" width="200" height="200" />
        <? else: ?>
            asdf
            <img src="nopic.jpg" width="200" height="200"/>
        <? endif; ?>
    </div>
    <div class="span8 well">
        <? if($product->has('manufacturer')): ?>
            <?=$product->getManufacturer()->getName();?>
            <hr/>
        <? endif; ?>
        <? if(!$product->has('options') && !$this->uomSelection) : ?>
            <input type="text" name="quantity" value="1">
            <input type="submit" value="Add To Cart"/>
            <hr/>
        <? endif; ?>
        <?=$product->getDescription(); ?>
    </div>
</div>

<? if(
    $product->has('options') || $product->has('specs')
    || $product->has('documents') || $this->uomSelection
): ?>
    <div class="tabbable" class="row">
        <ul class="nav nav-tabs">
            <? if($product->has('options') || $this->uomSelection) : ?>
                <li><a href="#config-buy" data-toggle="tab">Configure and Buy</a></li>
            <? endif; ?>
            <? if($product->has('specs')) : ?>
                <li><a href="#specs" data-toggle="tab">Specs</a></li>
            <? endif; ?>
            <? if($product->has('documents')) : ?>
                <li><a href="#documents" data-toggle="tab">Documents</a></li>
            <? endif; ?>
        </ul>
        <div class="tab-content">
            <? if($product->has('options') || $this->uomSelection) : ?>
                <div class="boundary tab-pane" id="config-buy">
                    <? foreach($product->getOptions() as $option) : ?>
                        <?=$this->partial($pdir . 'option.phtml', array('option' => $option, 'tree' => '[options]')); ?>
                    <? endforeach; ?>
                    <div id="uoms">
                        <?=$this->speckCatalogUomsToCart($product); ?>
                    </div>
                </div>
            <? endif; ?>
            <? if($product->has('specs')) : ?>
                <div class="boundary tab-pane" id="specs">
                    <? foreach($product->getSpecs() as $spec) : ?>
                        <?=$this->partial($pdir . 'spec.phtml', array('spec' => $spec)); ?>
                    <? endforeach; ?>
                </div>
            <? endif; ?>
            <? if($product->has('documents')) : ?>
                <div class="boundary tab-pane" id="documents">
                    <? foreach($product->getDocuments() as $document) : ?>
                        <?=$this->partial($pdir . 'document.phtml', array('document' => $document)); ?>
                    <? endforeach; ?>
                </div>
            <? endif; ?>
        </div>
        <hr/>
    </div>
    <script>
        jQuery(document).ready(function(){
            var $ = jQuery;
            $('.tab-content').children().first().addClass('active')
            $('.nav-tabs').children().first().addClass('active')
            uomBuilders($('form#configure-buy'), valid_builders);
        });
    </script>
<? endif; ?>
</form>
