<? $pdir = '/speck-catalog/product/option/'; ?>
<? if($option->has('choices')): ?>
    <div class="option" style="margin-left:25px; border:1px solid #ddd; margin-bottom:5px; margin-right:25px; padding:10px">
        <strong><?=$option; ?><?=($option->getRequired() ? '*' : ''); ?>:</strong><br/>
        <? if ($option->has('instruction')):?>&nbsp;&nbsp;&nbsp;(<?=$option->getInstruction();?>)<br/><? endif; ?>
        <? $listType = $option->getOptionTypeId(); ?>
        <? if ('1' === $listType): ?>
            <?=$this->partial($pdir . 'select.phtml', array('option' => $option)); ?>
        <? elseif ('2' === $listType): ?>
            <?=$this->partial($pdir . 'radio.phtml', array('option' => $option)); ?>
        <? elseif ('3' === $listType): ?>
            <?=$this->partial($pdir . 'checkbox.phtml', array('option' => $option)); ?>
        <? endif; ?>
    </div>
<? endif; ?>
