<?php

return array(
    'service_manager' => array(
        'shared' => array(
            'speckcatalog_cart_item_meta'    => false,
            'speckcatalog_option_form'       => false,
            'speckcatalog_choice_form'       => false,
            'speckcatalog_product_form'      => false,
            'speckcatalog_uom_form'          => false,
            'speckcatalog_image_form'        => false,
            'speckcatalog_spec_form'         => false,
            'speckcatalog_availability_form' => false,
            'speckcatalog_product_uom_form'  => false,
        ),
        'invokables' => array(
            'speckcatalog_cart_item_meta'           => 'SpeckCatalog\Model\CartItemMeta',
            'speckcatalog_product_service'          => 'SpeckCatalog\Service\Product',
            'speckcatalog_category_service'         => 'SpeckCatalog\Service\Category',
            'speckcatalog_company_service'          => 'SpeckCatalog\Service\Company',
            'speckcatalog_option_service'           => 'SpeckCatalog\Service\Option',
            'speckcatalog_choice_service'           => 'SpeckCatalog\Service\Choice',
            'speckcatalog_product_uom_service'      => 'SpeckCatalog\Service\ProductUom',
            'speckcatalog_uom_service'              => 'SpeckCatalog\Service\Uom',
            'speckcatalog_document_service'         => 'SpeckCatalog\Service\Document',
            'speckcatalog_availability_service'     => 'SpeckCatalog\Service\Availability',
            'speckcatalog_spec_service'             => 'SpeckCatalog\Service\Spec',
            'speckcatalog_sites_service'            => 'SpeckCatalog\Service\Sites',
            'speckcatalog_cart_service'             => 'SpeckCatalog\Service\CatalogCartService',
            'speckcatalog_form_service'             => 'SpeckCatalog\Service\FormService',
            'speckcatalog_option_form'              => 'SpeckCatalog\Form\Option',
            'speckcatalog_choice_form'              => 'SpeckCatalog\Form\Choice',
            'speckcatalog_uom_form'                 => 'SpeckCatalog\Form\Uom',
            'speckcatalog_company_form'             => 'SpeckCatalog\Form\Company',
            'speckcatalog_category_form'            => 'SpeckCatalog\Form\Category',
            'speckcatalog_spec_form'                => 'SpeckCatalog\Form\Spec',
            'speckcatalog_image_form'               => 'SpeckCatalog\Form\Image',
            'speckcatalog_document_form'            => 'SpeckCatalog\Form\Document',
            'speckcatalog_spec_form_filter'         => 'SpeckCatalog\Filter\Spec',
            'speckcatalog_document_form_filter'     => 'SpeckCatalog\Filter\Document',
            'speckcatalog_product_form_filter'      => 'SpeckCatalog\Filter\Product',
            'speckcatalog_product_uom_form_filter'  => 'SpeckCatalog\Filter\ProductUom',
            'speckcatalog_option_form_filter'       => 'SpeckCatalog\Filter\Option',
            'speckcatalog_choice_form_filter'       => 'SpeckCatalog\Filter\Choice',
            'speckcatalog_category_form_filter'     => 'SpeckCatalog\Filter\Category',
            'speckcatalog_availability_form_filter' => 'SpeckCatalog\Filter\Availability',
            'speckcatalog_product_mapper'           => 'SpeckCatalog\Mapper\Product',
            'speckcatalog_category_mapper'          => 'SpeckCatalog\Mapper\Category',
            'speckcatalog_company_mapper'           => 'SpeckCatalog\Mapper\Company',
            'speckcatalog_option_mapper'            => 'SpeckCatalog\Mapper\Option',
            'speckcatalog_choice_mapper'            => 'SpeckCatalog\Mapper\Choice',
            'speckcatalog_product_uom_mapper'       => 'SpeckCatalog\Mapper\ProductUom',
            'speckcatalog_image_mapper'             => 'SpeckCatalog\Mapper\Image',
            'speckcatalog_document_mapper'          => 'SpeckCatalog\Mapper\Document',
            'speckcatalog_uom_mapper'               => 'SpeckCatalog\Mapper\Uom',
            'speckcatalog_availability_mapper'      => 'SpeckCatalog\Mapper\Availability',
            'speckcatalog_spec_mapper'              => 'SpeckCatalog\Mapper\Spec',
            'speckcatalog_sites_mapper'             => 'SpeckCatalog\Mapper\Sites',
        ),
    ),
);
