<form id="choice-<?=$choice->getChoiceId();?>" class="live-form">

    <input type="hidden" name="choice_id" value="<?=$choice->getChoiceId();?>"/>
    <input type="hidden" name="product_id" value="<?=$choice->getProductId();?>"/>

    <div class="row">
        <div class="span3">
            <span class="smallcaps">name</span><br/>
            <input name="override_name" class="span3" type="text" value="<?=$choice->getOverrideName();?>"/>
        </div>  
        <div class="span2">
            <span class="smallcaps">price discount</span><br/>
            <input name="priceDiscount" class="span2" type="text"/>
        </div>
        <div class="span2">
            <span class="smallcaps">price increase</span><br/>
            <input name="priceIncrease" class="span2" type="text"/>
        </div>
    </div>

</form><br/>  
