<form id="document-<?=$document->getRecordId();?>" class="live-form">

    <input type="hidden" name="record_id" value="<?=$document->getRecordId();?>"/>
    <div class="row">
        <div class="span3">
            <span class="smallcaps">label</span><br/>
            <input name="label" class="span3" type="text" value="<?=$document->getLabel();?>"/>
        </div>  
        <div class="span3">
            <span class="smallcaps">filename</span><br/>
            <input name="file_name" class="span3" type="text" value="<?=$document->getFilename();?>"/>
        </div>
    </div>
    <a href="<?=$document->getFullPath();?>" target="_blank"><?=$document->getFullPath();?></a>

</form><br/>  
