<? $pdir = '/catalog-manager/partial/'; ?>
<form id="productUom-<?=$productUom->getRecordId();?>" class="live-form">
    
    <input type="hidden" name="record_id" value="<?=$productUom->getRecordId();?>"/>
    <input type="hidden" name="parent_product_id" value="<?=$productUom->getParentProductId();?>"/>
    
    <div class="row quarter-pad">
        <div class="span4">
            <div class="row">
                <div class="span2">
                    <span class="smallcaps">uom</span><br/>
                    <select name="uom_code" class="span2">
                        <?=$this->partial($pdir.'form/select-options.phtml', array(
                            'data' => $productUom->getUoms(),
                            'getIdMethod' => 'getUomCode',
                            'selectedId'  => $productUom->getUomCode(),
                            'getNameMethod' => 'getName',
                        ));?>
                    </select>  
                </div>
                <div class="span1">
                    <span class="smallcaps">qty</span><br/>
                    <input class="span1" type="text" name="quantity" value="<?=$productUom->getQuantity();?>"/>
                </div>  
            </div>
            <div class="row">
                <div class="span2 input-prepend">
                    <span class="smallcaps">retail</span><br/>
                    <span class="add-on">$</span>
                    <input class="span1" type="text" name="retail" value="<?=$productUom->getRetail();?>"/>
                </div>
                <div class="span2 input-prepend">
                    <span class="smallcaps">price</span><br/>
                    <span class="add-on">$</span>
                    <input class="span1" type="text" name="price" value="<?=$productUom->getPrice();?>"/>
                </div>
            </div>
        </div> 
    </div>

</form><br/>
