<? $pdir = '/catalog-manager/partial/'; ?>

<?

$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'asdf');

echo $this->form()->openTag($form);
?>
<dl class="zend_form">
    <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
    <dd><?php echo $this->formInput($form->get('name')); ?></dd>
    <dt><?php echo $this->formLabel($form->get('description')); ?></dt>
    <dd><?php echo $this->formInput($form->get('description')); ?></dd>

</dl>
<form id="product-<?=$product->getRecordId();?>" class="live-form">

    <input type="hidden" name="record_id" value="<?=$product->getRecordId();?>"/>
    <input type="hidden" name="type" value="<?=$product->getType();?>"/>

    <div class="row">
        <div class="span2">
            <? if ($product->has('images')) : ?>
                <? foreach($product->getImages() as $image) : ?>
                    <img class="img hover_fullsize" src="<?=$image->getFullPath();?>"/>
                    <? break; ?>
                <? endforeach; ?>
            <? endif; ?>
        </div>
        <div class="span6">
            <span class="smallcaps">name</span><br/>
            <input name="name" class="span6" type="text" value="<?=$product->getName();?>"/><br/>
            <span class="smallcaps">description</span><br/>
            <textarea name="description" rows="4" class="span6"><?=$product->getDescription();?></textarea>
        </div>
        <div class="span3">
            <? if(isset($product) && $product->isItem()) : ?>
                    <span class="smallcaps">manufacturer</span><br/>
                    <select name="manufacturer_company_id" class="span3">
                        <?=$this->partial($pdir.'form/select-options.phtml', array(
                            'data' => $product->getCompanies(),
                            'getIdMethod' => 'getRecordId',
                            'selectedId'  => $product->getManufacturerCompanyId(),
                            'getNameMethod' => 'getName',
                        ));?>
                    </select>
                    <span class="smallcaps">item/part number</span><br/>
                    <input name="item_number" class="span3" type="text" value="<?=$product->getItemNumber();?>"/>
                    <span class="smallcaps">hcpcs</span><br/>
                    <input name="hcpcs" class="span3" type="text" value=""/>
            <? endif; ?>
        </div>
    </div>

</form>
