<? $pdir = '/catalog-manager/partial/'; ?>
<form id="product-<?=$product->getRecordId();?>" class="live-form">
            
    <input type="hidden" name="record_id" value="<?=$product->getRecordId();?>"/>
    <input type="hidden" name="type" value="<?=$product->getType();?>"/>

    <div class="row">
        <div class="span8">
            <span class="smallcaps">name</span><br/>
            <input name="name" class="span8" type="text" value="<?=$product->getName();?>"/><br/>
            <span class="smallcaps">description</span><br/>
            <textarea name="description" rows="4" class="span8"><?=$product->getDescription();?></textarea>
        </div>
        <div class="span3">
            <? if(isset($product) && $product->isItem()) : ?>
                    <span class="smallcaps">manufacturer</span><br/>
                    <select name="manufacturer_company_id" class="span3">
                        <?=$this->partial($pdir.'form/select-options.phtml', array(
                            'data' => $product->getCompanies(),
                            'getIdMethod' => 'getCompanyId',
                            'selectedId'  => $product->getManufacturerCompanyId(),
                            'getNameMethod' => 'getName',
                        ));?>
                    </select>

                    <span class="smallcaps">item/part number</span><br/>
                    <input name="item_number" class="span3" type="text" value="<?=$product->getItemNumber();?>"/>
                    <span class="smallcaps">hcpcs</span><br/>
                    <input name="hcpcs" class="span3" type="text" value=""/>
            <? endif; ?>    
        </div> 
    </div>            

</form>
