<form id="spec-<?=$spec->getSpecId();?>" class="live-form">

    <input type="hidden" name="spec_id" value="<?=$spec->getSpecId();?>"/>
    <input type="hidden" name="product_id" value="<?=$spec->getProductId();?>"/>
    <div class="row">
        <div class="span3">
            <span class="smallcaps">label</span><br/>
            <input name="label" class="span3" type="text" value="<?=$spec->getLabel();?>"/>
        </div>  
        <div class="span3">
            <span class="smallcaps">value</span><br/>
            <input name="value" class="span3" type="text" value="<?=$spec->getValue();?>"/>
        </div>  
    </div>

</form><br/>  
