<div class="row span11">
    <? foreach ($forms as $uomString => $form) : ?>
        <div class="product-uom-wrap span3 row well">
            <?=$uoms[$uomString]['display_name']; ?>
            <div class="row">
                <div class="span1">
                    <?= $this->formInput($form->get('quantity')->setAttribute('class', 'span1')); ?>
                </div>
                <? $submit = $form->get('submit'); ?>
                <? $class = $submit->getAttribute('class') . ' span2'; ?>
                <?= $this->formButton($submit->setAttribute('class', $class)); ?>
            </div>
        </div>
    <? endforeach; ?>
</div>
