<div style="row" class="span12">
    <div class="span3">
        <?= $this->formLabel($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?= $this->formLabel($form->get('quantity')); ?>
    </div>
    <div class="span2" style="align:bottom">
        &nbsp;<br/>
    </div>
</div>
<div style="row" class="span12">
    <div class="span3">
        <?= $this->formSelect($form->get('uom')); ?>
    </div>
    <div class="span1">
        <?= $this->formInput($form->get('quantity')->setAttribute('class', 'span1')); ?>
    </div>
    <div class="span2" style="align:bottom">
        <? $submit = $form->get('submit'); ?>
        <? $class = $submit->getAttribute('class') . ' span2'; ?>
        <?= $this->formButton($submit->setAttribute('class', $class)); ?>
    </div>
</div>
