


<h3>Products</h3>

<? //$this->paginator = $sessionPaginator;?>
<?//=$this->render('/catalogmanager/partial/entity-list.phtml'); ?>  

<form action='/swmimporter/import-product'>
    <input type="text" name="id"> import a product by id
</form>

<? if(isset($results)) :?>
    <? foreach($results as $model) : ?>
    <a href="/catalogmanager/product?id=<?=$model->getId();?>"><?=$model;?></a><br/>
<? endforeach; ?>
<? endif; ?>
