<? $pdir = '/catalogmanager/partial/'; ?>

<!-- tabs -->
<ul class="tabs" data-tabs="tabs">
    <li class="this-product"><a href="#this-product">This Product</a></li>
    <li class="parent-choices"><a href="#parent-choices">Parent Choices</a></li>
</ul>
<!-- /tabs -->

<!-- panes -->
<div id="my-tab-content" class="tab-content">
    
    <!--"This Product" Pane -->
    <div id="this-product">

            <!-- tabs -->
            <ul class="tabs" data-tabs="tabs">
                <li class="product"><a href="#product">Product</a></li>
                <li class="options"><a href="#options">Options</a></li>
                <li class="specs"><a href="#specs">Specs</a></li>
                <li class="features"><a href="#features">Features</a></li>
                <li class="documents"><a href="#documents">Documents</a></li>
            </ul> 
            <!-- /tabs -->

            <!-- panes -->
            <div id="my-tab-content" class="tab-content">

                <!-- "This Product > Product" Pane -->
                <div class="tab-pane entity" id="product">
                    <div class="entity-header">
                        <div><span class="label entity-title">Product</span></div>
                    </div>
                    <?=$this->partial($pdir.'form/product.phtml', array('product' => $product));?><br/>

                    <? if($product->isItem()) :?>
                            <div class="list-wrap">
                                <div class="list-items">
                                    <? if ($product->hasUoms()) : ?>
                                        <? foreach($product->getUoms() as $itemUom) : ?>
                                            <?=$this->partial($pdir.'item-uom.phtml', array('itemUom' => $itemUom));?>
                                        <? endforeach; ?>
                                    <? else : ?>
                                        <?=$this->partial($pdir.'item-uom.phtml', array('courtesy' => 1));?>
                                    <? endif; ?>
                                </div>
                                <div class="row">
                                    <?=$this->render($pdir.'item-uom.phtml');?>
                                    <?=$this->partial($pdir.'add.phtml', array('function' => 'add-button', 'name' => 'uom'));?>
                                </div>
                            </div>
                    <? endif; ?> 
                </div>
                <!-- /"This Product > Product" Pane -->

                <!-- "This Product > Options" Pane -->
                <div class="tab-pane" id="options">
                    <div class="list-wrap">
                        <div class="list-items">
                            <? if (count($product->getOptions()) > 0) : ?>
                                <? foreach ($product->getOptions() as $option) : ?>
                                    <?=$this->partial($pdir.'option.phtml', array('option' => $option));?>
                                <? endforeach; ?>
                            <? else : ?>
                                <?=$this->partial($pdir.'option.phtml', array('courtesy' =>1));?>
                            <? endif; ?>
                        </div>
                        <div class="row">
                            <?=$this->render($pdir.'option.phtml'); ?>
                            <?=$this->partial($pdir.'add.phtml', array('function' => 'import-search', 'name' => 'option'));?>
                            <?=$this->partial($pdir.'add.phtml', array('function' => 'add-button', 'name' => 'option'));?>
                        </div>
                    </div>

                </div>
                <!-- /"This Product > Options" Pane -->
                
                <!-- "This Product > Specs" Pane -->
                <div class="tab-pane" id="specs">
                    <div class="add-new">
                        add a spec
                    </div>
                </div>
                <!-- /"This Product > Specs" Pane -->

            </div>
            <!-- /panes -->

    </div>
    <!-- /"This Product" Pane -->

    <!-- "Parent Choices" Pane -->
    <div class="tab-pane" id="parent-choices">
            <? if (count($product->getParentChoices()) > 0) : ?>
                <?=$this->partial($pdir.'entity-list.phtml', array('paginator' => $parentChoicesPaginator)); ?>       
            <? endif; ?>  
    </div>
    <!-- /"Parent Choices" Pane -->

</div>
<!-- /panes -->

