
<!-- tabs -->
<ul class="tabs" data-tabs="tabs">
    <li class="this-product"><a href="#this-product">This Product</a></li>
    <li class="parent-choices"><a href="#parent-choices">Parent Choices</a></li>
</ul>
<!-- /tabs -->

<!-- panes -->
<div id="my-tab-content" class="tab-content">
    
    <!--"This Product" Pane -->
    <div id="this-product">

            <!-- tabs -->
            <ul class="tabs" data-tabs="tabs">
                <li class="product"><a href="#product">Product</a></li>
                <li class="options"><a href="#options">Options</a></li>
            </ul> 
            <!-- /tabs -->

            <!-- panes -->
            <div id="my-tab-content" class="tab-content">

                <!-- "This Product > Product" Pane -->
                <div class="tab-pane" id="product">
                        <? if($product->getType() === 'product') : ?>
                            <div class="row show-grid product">
                            <div class="span5">
                                <? $this->form = $this->forms['form']; ?>
                                <?=$this->render('catalogmanager/partial/editform.phtml');?>
                            </div>
                            <div class="span11">
                                <? if($product->getItem()) :?>
                                    <? $this->item = $product->getItem(); ?>
                                    <?=$this->render('/catalogmanager/partial/product/item.phtml');?>
                                <? else : ?>
                                    something is broken, product should always have item!                                
                                <? endif; ?>
                            </div>
                            </div>
                        <? else: ?>
                            <? $this->form = $this->forms['form']; ?>
                            <?=$this->render('/catalogmanager/partial/editform.phtml');?>
                        <? endif; ?> 
                </div>
                <!-- /"This Product > Product" Pane -->

                <!-- "This Product > Options" Pane -->
                <div class="tab-pane" id="options">
                        <? $this->class = 'option'; ?>
                        <?=$this->render('/catalogmanager/partial/add.phtml');?>
                        <? if (count($product->getOptions()) > 0) : ?>
                            <div class="row">
                            <? foreach ($product->getOptions() as $this->option) : ?>
                                <div class="span16">
                                <hr>
                                <?=$this->render('/catalogmanager/partial/product/option.phtml');?>
                                </div>
                            <? endforeach; ?>
                            </div>
                        <? endif; ?>
                        <div class="add-new">
                                <? $this->option = null; ?>
                                <?=$this->render('/catalogmanager/partial/product/option.phtml');?>
                        </div>

                </div>
                <!-- "This Product > Options" Pane -->

            </div>
            <!-- /panes -->

    </div>
    <!-- /"This Product" Pane -->

    <!-- "Parent Choices" Pane -->
    <div class="tab-pane" id="parent-choices">
            <? if (count($product->getParentChoices()) > 0) : ?>
                <? $this->paginator = $parentChoicesPaginator;?>
                <?=$this->render('/catalogmanager/partial/entity-list.phtml'); ?>       
            <? else : ?>
            (none)
            <? endif; ?>  
    </div>
    <!-- /"Parent Choices" Pane -->

</div>
<!-- /panes -->
