<?php 
    if($results){
        foreach($results as $entity){
            $class = explode('\\', get_class($entity)); $className = array_pop($class);
            $method = 'get'.$className.'Id';
            $entityId = $entity->$method();
            $title = ''; 
            foreach($entity->toArray() as $key => $val){
                $val = htmlentities($val); 
                $title.="| {$key}: {$val} |";
            } 
            $link = '<a href="#" class="modal-search-result" data-placement="below" rel="popover" ';
            $link .= 'data-content="' . $title                 . '" ';
            $link .= 'parentId="'     . $parentId              . '" ';
            $link .= 'entityId="'     . $entityId              . '" ';
            $link .= 'className="'    . strtolower($className) . '" ';
            if(isset($callback))        $link .= 'callback="'        . $callback        . '" ';
            if(isset($parentClassName)) $link .= 'parentClassName="' . $parentClassName . '" ';
            if(isset($newPartialName))  $link .= 'newPartialName="'  . $newPartialName  . '" ';
            $link .= '>' . $entity->__toString() . '</a><br/>';

            echo $className . ' - ' . $link;
        }
    }else{
        echo 'No Results';
    } 
