<? if($results) : ?>
    <? foreach($results as $entity) : ?>
        <? 
        $class = explode('\\', get_class($entity)); $className = array_pop($class);
        $method = 'get'.$className.'Id';
        $entityId = $entity->$method();
        if(isset($parentClassName)){$pc = 'parentClassName = "' . $parentClassName . '" ';}else{$pc = '';}
        $title = ''; foreach($entity->toArray() as $key => $val){$title.="| {$key}: {$val} |";} 
        ?>
        <?=$className;?> - <a href="#" class="modal-search-result" data-content="<?=$title;?>" rel="popover" data-placement="below" entityId="<?=$entityId;?>" parentId="<?=$parentId;?>" <?=$pc;?> className="<?=strtolower($className);?>"><?=$entity;?></a><br/>

    <? endforeach; ?>

<? else: ?>
    No Results
<? endif; ?>
