 <? $pdir = '/catalog-manager/partial/'; ?>


<h3>Products</h3>

<? //$this->paginator = $sessionPaginator;?>
<?//=$this->render('/catalogmanager/partial/entity-list.phtml'); ?>  

<form action='/swmimporter/import-product'>
    <input type="text" name="id"> import a product by id
</form>

<? if(isset($products)) :?>
    <?=count($products);?> Products
    <? foreach($products as $product) : ?>
            <?=$this->partial($pdir.'product.phtml', array('product' => $product));?>
    <? endforeach; ?>
<? endif; ?>
