<style>

    div.tree-cat{padding:2px; margin-top:10px; margin-bottom:10px border:1px solid #cccccc; background:#dddddd}
    div.tree-product{padding:2px; margin-top:10px; margin-bottom:10px; background:#ddeeff; border:1px solid #aaccff}

    div.tree-cat-placeholder{background:#cccccc; margin:1px }
    div.tree-product-placeholder{background:#aaccff; margin:1px}

    div.tree-cat-title{cursor:move; padding-bottom:4px}
    div.tree-product-title{cursor:move}

    div.tree-cat-cats{padding:3px; padding-top:5px; padding-bottom:5px; min-height:10px; background:#eeeeee; border:1px solid #cccccc;}
    div.tree-cat-products{padding:3px; padding-top:5px; padding-bottom:5px; min-height:10px; background:#eef5ff; border:1px solid #aaccff}


</style>

</style>
<div class="row">
    <?= $this->speckCatalogManagerSideNav(); ?>

    <div class="span7">
        <h4>Site Tree</h4>
        <select id="site-select" class="span4">
            <option value=''>-- Choose a Site --</option>
            <? foreach($sites as $site) : ?>
                <option value="<?=$site->getSiteId();?>"><?=$site->getName();?></option>
            <? endforeach; ?>
        </select>
        <div class="tree-cat-cats cat-sort" id="option-tree" style="max-height:600px; height:600px; overflow-y:scroll">select a site from the above dropdown</div>
    </div>
    <div class="span3 tabbable">

        <ul class="nav nav-tabs">
            <li class="active"><a href="#products" data-toggle="tab">Find Products</a></li>
            <li><a href="#categories" data-toggle="tab">Find Categories</a></li>
        </ul>

        <div class="tab-content">
            <div id="products" class="tab-pane active">
                <input type="text" class="span3" id="search-product">
                <div class="tree-cat-products product-clone" id="product-search-results" style="max-height:300px; height:300px; overflow-y:scroll">
                    search for products above
                </div>
            </div>
            <div id="categories" class="tab-pane">
                <input type="text" class="span3" id="search-category">
                <div class="tree-cat-cats cat-clone" id="category-search-results" style="max-height:300px; height:300px; overflow-y:scroll">
                    search for categories above
                </div>
            </div>
        </div><!-- /tab-content -->

    </div><!-- /tabbable -->
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('select#site-select').live('change', function(){
            getSiteTree();
            categorySortable();
        })

        $('input#search-product').live('change', function(){
            if($(this).val().length > 2) {
                $.post('/admin/catalogmanager/categories/search/product/' + $(this).val(), null, function(html){
                    $('div#product-search-results').html(html);
                    categorySortable();
                })
            }
        })
        $('input#search-category').live('change', function(){
            if($(this).val().length > 2) {
                $.post('/admin/catalogmanager/categories/search/category/' + $(this).val(), null, function(html){
                    $('div#category-search-results').html(html);
                    categorySortable();
                })
            }
        })
        function categorySortable()
        {
            $('.cat-sort').sortable({
                connectWith:['.cat-sort']
                , placeholder: 'tree-cat tree-cat-placeholder'
                , handle: '.title'
                , tolerance: 'pointer'
                , revert : true
                , opacity: 0.3
            }).disableSelection();

            $('.product-sort').sortable({
                connectWith:['.product-sort']
                , placeholder: 'tree-product tree-product-placeholder'
                , handle: '.title'
                , tolerance: 'pointer'
                , revert : true
                , opacity: 0.3
            }).disableSelection();

            $('.cat-clone div.tree-cat').draggable({
                connectToSortable:'.cat-sort'
                , placeholder: 'tree-cat tree-cat-placeholder'
                , handle: '.title'
                , opacity: 0.3
                , helper: 'clone'
            }).disableSelection();

            $('.product-clone div.tree-product').draggable({
                connectToSortable:'.product-sort'
                , placeholder: 'tree-product tree-product-placeholder'
                , handle: '.title'
                , opacity: 0.3
                , helper: 'clone'
            }).disableSelection();

        }
        function getSiteTree(){
            if($('select#site-select').val()){
                $.post('/admin/catalogmanager/category-tree-preview/' + $('select#site-select').val(), null, function(html){
                    $('div#option-tree').html(html);
                })
            } else {
                $('div#option-tree').html('');
            }
        }
    })
</script>
