<div class="row">
    <div class="span12">
        <div id="products">
            <h3>Products</h3>
            <a href="/admin/catalogmanager/new-product">+ New Product</a><br/><br/>
            <? if(isset($products)) :?>
                <a href="/admin/catalogmanager/products"><?=count($products);?> Products</a>
            <? endif; ?>
        </div>
        <div class="hr"><hr/></div>
        <div id="categories">
            <h3>Categories</h3>
        </div>
        <div class="hr"><hr/></div>
    </div>

</div>
