<div class="row">
    <a href="<?=$this->url('zfcadmin/catalogmanager/new-product'); ?>" class="btn">New Product</a>
    <hr/>
    <div class="row-fluid">
        <? foreach($products as $product) : ?>
            <div class="span1">
                <b><?=$product->getProductId(); ?></b>
            </div>
            <div class="span1">
                <?=($product->getTypeId() === 1) ? '(Shell) ' : '(Product)'; ?>
            </div>
            <div class="span4">
                <a href="/admin/catalogmanager/product/<?=$product->getProductId();?>"><?=$product;?></a>
            </div>
        <? endforeach; ?>
    </div>
</div>
