<script type="text/javascript">

    function showUomsForProduct(productId, uomString, quantity)
    {
        var data = { product_id : productId, uom_string : uomString, quantity : quantity }
        $.post('/partial/uoms', data, function(html){ $('#uom_select').html(html); })
    }

    function getNewUomString(pid)
    {
        var str = $('input.select-product-uom:checked').val()
            || $('select.select-product-uom option:selected').val()
            || $('input.select-product-uom').val()
        if (str) {
            var spl = str.split(':')
            return pid + ':' + spl[1] + ':' + spl[2];
        }
        return '';
    }

    function matchChoicesToProduct()
    {
        var choiceIds = [];
        $('select.product_builder').each(function(){ choiceIds.push($(this).val()); });
        $('input.product_builder:checked').each(function(){ choiceIds.push($(this).val()); });
        var quantity = $('input#quantity-to-cart').val() || 1;
        for (var pid in builders) {
            if (builders[pid] === choiceIds.join(',')) {
                showUomsForProduct(pid, getNewUomString(pid), quantity);
            }
        }
    }

    $('input.product_builder, select.product_builder').live('change', function(){
        matchChoicesToProduct();
    });

</script>
