<? $pdir = '/catalog/catalog-manager/partial/'; ?>

<div class="boundary contrastbg half-pad" id="<?=$category->getCategoryId();?>">
    <div class="entity-header">
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-file"></i></div>
        <div class="title sort-handle">&nbsp; <?=$category;?></div>
    </div>
    <div class="entity-content initialcol">
        <?=$this->speckCatalogRenderForm($category);?>
        <div class="list-wrap">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;categories</span><br/>
            </div>
            <div class="list-items">
                <?=$this->speckCatalogRenderChildren($category->getCategories()); ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->speckCatalogAdderHelper('addButton', 'category', $category); ?>
            </div>
        </div>
        <div class="list-wrap">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;products</span><br/>
            </div>
            <div class="list-items">
                <?=$this->speckCatalogRenderChildren($category->getProducts()); ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->speckCatalogAdderHelper('addButton', 'product', $category); ?>
            </div>
        </div>
    </div>
</div>
