<? foreach ($children as $child) : ?>
    <? if($type === 'product') : ?>
        <div class="tree-product"><b>:P: </b><?= $child ;?></div>
    <? else : ?>
        <div class="tree-cat">
            <div class="tree-cat-title"><b>:C: </b><?= $child ;?></div>
            <div class="tree-cat-cats"></div>
            <div class="tree-cat-products"></div>
        </div>
    <? endif; ?>
<? endforeach; ?>
