<?
$formHelper = $this->speckCatalogForm($choice, 'choice');
$keyFields = $formHelper->getKeyFields();
$parentOptionKeyFields = $this->SpeckCatalogForm($choice->getParent(), 'option')->getKeyFields()
?>
<div class="choice whitebg boundary shadow" id="<?= $choice->getKey(); ?>" >
    <div class="entity-header">
        <div class="collapser left"><i class="icon-chevron-down initialCollapse"></i></div>
        <? if($choice->has('parentOptions')) : ?>
            <div class="left"><i class="icon-eye-open" title="This choice is shared <?=count($choice->getParentOptions());?> times"></i></div>
        <? endif; ?>
        <? if ($choice->has('options')) : ?>
            <div class="left"><span class="icon-list" title="has options"></span></div>
        <? elseif($choice->has('product')) : ?>
            <div class="left"><span class="icon-tag"></span></div>
        <? endif; ?>
        <div class="title sort-handle collapser left">&nbsp; <?=$choice;?></div>
        <div class="remover right">
            <?= $this->speckCatalogAdderHelper()->removeChild('option', $parentOptionKeyFields, 'choice', $keyFields); ?>
        </div>
    </div>
    <div class="entity-content">
        <?=$formHelper->renderForm(); ?>
        <? if($choice->has('product')) : ?>
            <?=$this->speckCatalogRenderChildren('product', array($choice->getProduct()));?>
        <? else: ?>
            <div class="list-wrap half-pad">
                <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                    <span class="smallcaps">&nbsp;option groups</span><br/>
                </div>
                <div class="list-items" data-type="option" data-parent="choice" data-parent_key="<?= $choice->getKey(); ?>">
                    <?=$this->speckCatalogRenderChildren('option', $choice->getOptions());?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->speckCatalogAdderHelper()->addNew('option', 'choice', $keyFields); ?>
                </div>
            </div>
        <? endif; ?>
    </div>
</div>
