<? $pdir = '/catalog/catalog-manager/partial/'; ?>

<? if(isset($bg)){ $bg=$bg; }else{ $bg='contrastbg'; } ?>
<? if(isset($collapse)){ $collapse='initialCollapse';} else { $collapse='';} ?>
<div class="boundary <?=$bg;?>" id="<?=$image->getMediaId();?>" >
    <div class="entity-header">
        <div class="collapser"><i class="icon-chevron-down <?=$collapse;?>"></i></div>
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div><i class="icon-picture"></i></div>
        <div class="title sort-handle collapser">&nbsp; <?=$image;?></div>
    </div>
    <div class="entity-content initialcol">
        <?=$this->partial($pdir.'form/image.phtml', array('image' => $image));?>
    </div>
</div>
