<?
    $formHelper = $this->speckCatalogForm($option, 'option');
    $optionKeyFields = $formHelper->getKeyFields();

    $parentProductKeyFields = $this->speckCatalogForm($option->getParent(), 'product')->getKeyFields();
?>


<div id="<?=$option->getKey();?>" class="option contrastbg boundary shadow">

    <div class="entity-header">
        <div class="collapser left"><i class="icon-chevron-down"></i></div>
        <? if(1===1 || $option->isShared()) : ?>
            <? $count = count($option->getParentProducts()); ?>
            <div class="left"><i class="icon-eye-open" title="This option is shared <?=$count;?> times"></i></div>
        <? endif; ?>
        <div class="title sort-handle collapser left">&nbsp; <?=$option;?></div>
        <div class="remover right">
            <?= $this->speckCatalogAdderHelper()->removeChild('product', $parentProductKeyFields, 'option', $optionKeyFields); ?>
        </div>
    </div>
    <div class="entity-content">
        <?=$formHelper->renderForm(); ?>
        <div class="list-wrap">
            <hr class="hr" />
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;option group helper images</span>
            </div>
            <div class="list-items" type="image" parent="product">
                <? if ($option->has('images')) : ?>
                    <?=$this->speckCatalogRenderChildren('option_image', $option->getImages()); ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <div class="span5">
                    Upload Image
                    <?= $this->speckCatalogOptionImageUploader($optionKeyFields); ?>
                </div>
            </div>
        </div>

        <div class="list-wrap half-pad">
            <hr class="hr" />
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;options</span>
            </div>
            <div class="list-items" data-type="choice" data-parent="option" data-parent_key="<?= $option->getKey(); ?>">
                <?=$this->speckCatalogRenderChildren('choice', $option->getChoices()); ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->speckCatalogAdderHelper()->addNew('choice', 'option', $optionKeyFields); ?>
            </div>
        </div>
    </div>

</div>
