<? $pdir = '/catalog/catalog-manager/partial/'; ?>
<div class="existing contrastbg boundary" id="">
<div class="entity-header">
    <div class="collapser"><i class="icon-chevron-down"></i></div>
    <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
    <div class="title collapser">&nbsp;<?=$productUom;?></div>
</div>
    <div class="entity-content">
        <div class="row">
            <div class="span4">
                <? $formHelper = $this->speckCatalogForm($productUom, 'product_uom'); ?>
                <?=$formHelper->renderForm(); ?>
            </div>
            <div class="span6">
                <div class="list-wrap">
                    <div class="child-expand list-items-helper">
                        <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                        <div class="expand-all"><i class="icon-arrow-down"></i></div>
                        <span class="smallcaps">&nbsp;availabilities</span><br/>
                    </div>
                    <div class="list-items">
                        <?=$this->speckCatalogRenderChildren('availability', $productUom->getAvailabilities());?>
                    </div>
                    <div class="row list-items-helper">
                        <?=$this->speckCatalogAdderHelper()->addNew('availability', 'product_uom', $formHelper->getKeyFields()); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
