<? $pdir = '/catalog/catalog-manager/partial/'; ?>
<div class="boundary contrastbg" id="<?=$spec->getId();?>">
    <div class="entity-header">
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div class="title sort-handle">&nbsp; <?=$spec;?></div>
    </div>
    <div class="entity-content">
        <?=$this->partial($pdir.'form/spec.phtml', array('spec' => $spec));?>
    </div>
</div>
