<?php
    $formHelper = $this->speckCatalogForm($spec, 'spec');
?>
<div class="boundary contrastbg">
    <div class="entity-header">
        <div class="remover"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div class="title sort-handle">&nbsp; <?=$spec;?></div>
    </div>
    <div class="entity-content">
        <?= $formHelper->renderForm(); ?>
    </div>
</div>
