<?=$this->form()->openTag($form);?>

    <?= $this->originalFields; ?>
    <?= $this->formInput($form->get('product_id')); ?>
    <?= $this->formInput($form->get('uom_code')); ?>
    <?= $this->formInput($form->get('quantity')); ?>

    <div class="row">
        <div class="span5">
            <div class="row">
                <div class="span3">
                    <?=$this->formRow($form->get('distributor_id')); ?>
                </div>
                <div class="span2 input-prepend">
                    <?=$this->formLabel($form->get('cost')); ?>
                    <span class="add-on">$</span>
                    <?=$this->formInput($form->get('cost')); ?>
                </div>
            </div>
        </div>
    </div>

</form></br>
