<?
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'category-' . $category->getRecordId());
$form->setAttribute('class', 'live-form');

?>

<?=$this->form()->openTag($form);?>
    <?=$this->formInput($form->get('record_id')); ?>

    <div class="row">
        <div class="span3">
            <?=$this->formRow($form->get('name')); ?>
        </div>
    </div>

</form>
