<?
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'choice-' . $choice->getChoiceId());
$form->setAttribute('class', 'live-form');

?>

    <? if(false === $form->isValid()) : ?>
        <? var_dump($form->getData()); ?>
        <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Oh snap!</strong>
        Change a few things up and try submitting again.
        </div>
    <? endif; ?>
<?=$this->form()->openTag($form);?>

    <?=$this->formInput($form->get('option_id')); ?>
    <?=$this->formInput($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?=$this->formRow($form->get('override_name')); ?>
        </div>
        <div class="span2">
        </div>
        <div class="span2">
        </div>
    </div>

</form>
