<?
$form->prepare();
$form->setAttribute('id', 'company');
$form->setAttribute('class', 'live-form');
?>

<?=$this->form()->openTag($form);?>
    <?= $this->originalFields; ?>
    <?=$this->formInput($form->get('company_id')); ?>

    <div class="row">
        <div class="span3">
            <?=$this->formRow($form->get('name')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('phone')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('email')); ?>
        </div>
    </div>

</form>
