<?
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'company-' . $company->getCompanyId());
$form->setAttribute('class', 'live-form');

?>

<?=$this->form()->openTag($form);?>
    <?=$this->formInput($form->get('company_id')); ?>

    <div class="row">
        <div class="span3">
            <?=$this->formRow($form->get('name')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('phone')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('email')); ?>
        </div>
    </div>

</form>
