<?=$this->form()->openTag($form);?>
    <?= $this->originalFields; ?>
    <?= $this->formRow($form->get('document_id')); ?>
    <?= $this->formRow($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?= $this->formRow($form->get('label')); ?>
        </div>
        <div class="span3">
            <?= $this->formRow($form->get('file_name')); ?>
        </div>
    </div>

</form><br/>
