<form id="image-" class="live-form">

    <input type="hidden" name="parent_id" value="<?=$image->getParentId();?>"/>
    <div class="row">
        <div class="span1">
        <img class="img hover_fullsize" src="<?=$this->speckCatalogImage()->product($image);?>"/>
        </div>
        <div class="span3">
            <span class="smallcaps">label</span><br/>
            <input name="label" class="span3" type="text" value="<?=$image->getLabel();?>"/>
        </div>
        <div class="span3">
            <span class="smallcaps">filename</span><br/>
            <input name="file_name" class="span3" type="text" value="<?=$image->getFilename();?>"/>
        </div>
    </div>

</form><br/>
