<? $pdir = '/catalog/catalog-manager/partial/'; ?>

<?
$form->edit();
$form->prepare();
$form->setAttribute('id', 'product');
$form->setAttribute('class', 'live-form');
?>
<?=$this->form()->openTag($form);?>
    <?= $this->originalFields; ?>
    <?=$this->formInput($form->get('product_id')); ?>

    <? if(false === $form->isValid()) : ?>
        <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Oh snap!</strong>
        Change a few things up and try submitting again.
        </div>
    <? endif; ?>

    <div class="row">
        <div class="span2">
            <? if ($product->has('image')) : ?>
                <img class="img hover_fullsize" src="<?=$this->speckCatalogImage()->product($product->getImage());?>"/>
            <? endif; ?>
        </div>
        <div class="span6">
            <?=$this->formRow($form->get('name')); ?>
            <?=$this->formRow($form->get('description')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('manufacturer_id')); ?>
            <?=$this->formRow($form->get('product_type_id')); ?>
            <? if('2' == $product->getProductTypeId()) : ?>
                <?=$this->formRow($form->get('item_number')); ?>
            <? endif; ?>
        </div>
    </div>

</form>
