<?=$this->form()->openTag($form);?>
    <?= $this->formErrors; ?>
    <?= $this->originalFields; ?>
    <?=$this->formInput($form->get('product_id')); ?>

    <? if(false === $form->isValid()) : ?>
        <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Oh snap!</strong>
        Change a few things up and try submitting again.
        </div>
    <? endif; ?>

    <div class="row">
        <div class="span2">
            <? if ($product->has('image')) : ?>
                <img class="img hover_fullsize" src="<?=$this->speckCatalogImage()->product($product->getImage());?>"/>
            <? endif; ?>
        </div>
        <div class="span6">
            <?=$this->formRow($form->get('name')->setAttribute('class', 'span6')); ?>
            <?=$this->formRow($form->get('description')->setAttribute('class', 'span6')); ?>
        </div>
        <div class="span3">
            <?=$this->formRow($form->get('manufacturer_id')->setAttribute('class', 'span3')); ?>
            <?=$this->formRow($form->get('product_type_id')->setAttribute('class', 'span3')); ?>
            <? if('2' == $product->getProductTypeId()) : ?>
                <?=$this->formRow($form->get('item_number')->setAttribute('class', 'span3')); ?>
            <? endif; ?>
        </div>
    </div>

</form>
