<? $pdir = '/catalog/catalog-manager/partial/'; ?>
<?=$this->form()->openTag($form);?>
    <div class="form-messages"><?= $this->formErrors; ?></div>
    <?= $this->originalFields; ?>
    <?=$this->formInput($form->get('product_id')); ?>
    <div class="row quarter-pad">
        <div class="span4">
            <div class="row">
                <div class="span2">
                    <?=$this->speckCatalogManagerFormRow($form->get('uom_code')); ?>
                </div>
                <div class="span1">
                    <?=$this->speckCatalogManagerFormRow($form->get('quantity')); ?>
                </div>
            </div>
            <div class="row">
                <div class="span2 input-prepend">
                    <?=$this->formLabel($form->get('retail')); ?>
                    <span class="add-on">$</span>
                    <?=$this->formElement($form->get('retail')); ?>
                    <?=$this->formElementErrors($form->get('retail')); ?>
                </div>
                <div class="span2 input-prepend">
                    <?=$this->formLabel($form->get('price')); ?>
                    <span class="add-on">$</span>
                    <?=$this->formElement($form->get('price')); ?>
                    <?=$this->formElementErrors($form->get('price')); ?>
                </div>
            </div>
        </div>
    </div>

</form>
