<?=$this->form()->openTag($form);?>
    <?= $this->originalFields; ?>
    <?= $this->formRow($form->get('spec_id')); ?>
    <?= $this->formRow($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?= $this->formRow($form->get('label')->setAttribute('class', 'span3')); ?>
        </div>
        <div class="span3">
            <?= $this->formRow($form->get('value')->setAttribute('class', 'span3')); ?>
        </div>
    </div>

</form>
