<form id="spec-<?=$spec->getSpecId();?>" class="live-form">

    <input type="hidden" name="spec_id" value="<?=$spec->getSpecId();?>"/>
    <input type="hidden" name="product_id" value="<?=$spec->getProductId();?>"/>
    <div class="row">
        <div class="span3">
            <span class="smallcaps">label</span><br/>
            <input name="label" class="span3" type="text" value="<?=$spec->getLabel();?>"/>
        </div>
        <div class="span3">
            <span class="smallcaps">value</span><br/>
            <textarea name="value" class="span3" type="text" rows="1"><?=$spec->getValue();?></textarea>
        </div>
        <div class="span3">
            <span class="smallcaps">tab delimited(table)</span><br/>
            <textarea name="tab_delimited" class="span3" type="text" rows="1"><?=$spec->getTabDelimited();?></textarea>
        </div>
    </div>

</form>
