<?=$this->form()->openTag($form);?>
    <div class="form-messages"><?= $this->formErrors; ?></div>
    <?= $this->originalFields; ?>
    <?= $this->formRow($form->get('spec_id')); ?>
    <?= $this->formRow($form->get('product_id')); ?>

    <div class="row">
        <div class="span3">
            <?= $this->speckCatalogManagerFormRow($form->get('label')->setAttribute('class', 'span3')); ?>
        </div>
        <div class="span3">
            <?= $this->speckCatalogManagerFormRow($form->get('value')->setAttribute('class', 'span3')); ?>
        </div>
    </div>

</form>
