<? $pdir = '/catalog-manager/partial/'; ?>

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#category" data-toggle="tab">Category</a></li>
        <li><a href="#products" data-toggle="tab">Products</a></li>
    </ul>
 
    <div class="tab-content">

        <div class="active boundary tab-pane" id="category">

            <div class="entity-header hide"><div class="title"></div></div>
            <div class="entity-content">
                <?=$this->partial($pdir.'form/category.phtml', array('category' => $category));?><br/>
            </div>
            <div class="list-wrap half-pad">
            <div class="child-expand list-items-helper">
                <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                <div class="expand-all"><i class="icon-arrow-down"></i></div>
                <span class="smallcaps">&nbsp;child categories</span>
            </div>
            <div class="list-items">
                <? if ($category->hasCategories()) : ?>
                    <? foreach($category->getCategories() as $category) : ?>
                        <?=$this->partial($pdir.'category.phtml', array('category' => $category));?>
                    <? endforeach; ?>
                <? endif; ?>
            </div>
            <div class="row list-items-helper">
                <?=$this->partial($pdir.'add.phtml', array(
                    'function'        => 'import-search',
                    'searchClassName' => 'product',
                    'childClassName'  => 'product',
                    'newClassName'    => 'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $category->getCategoryId(),
                    'partialName'     => 'choice',
                ));?>    
                <?=$this->partial($pdir.'add.phtml', array(
                    'function' => 'add-button',
                    'newClassName'=>'choice',
                    'parentClassName' => 'option',
                    'parentId'        => $category->getCategoryId(),
                    'partialName'     => 'choice',
                ));?>
  
            </div>
        </div>
        </div>

        <div id="products" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>   
                </div>
                <div class="list-items">
                    <? if ($category->hasProducts()) : ?>
                        <? foreach ($category->getProducts() as $product) : ?>
                            <?=$this->partial($pdir.'product.phtml', array('product' => $product));?>
                        <? endforeach; ?>
                    <? endif; ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'import-search',
                        'searchClassName' => 'product',
                        'className'       => 'product',
                        'parentClassName' => 'category',
                        'parentId'        => $category->getCategoryId(),
                        'partialName'     => 'product',
                    ));?>
                </div>
            </div> 
        </div>

    </div>
</div><!--/tabbable-->

<?=$this->render($pdir.'modal.phtml'); ?>
