<? $pdir = '/catalog-manager/partial/'; ?>
<div class="list-wrap half-pad">
    <div class="child-expand list-items-helper">
        <div class="collapse-all"><i class="icon-arrow-up"></i></div>
        <div class="expand-all"><i class="icon-arrow-down"></i></div>
        <span class="smallcaps">&nbsp;categories</span>
    </div>
    <div class="list-items">
        <? foreach($categories as $category) : ?>
            <?=$this->partial($pdir.'category.phtml', array('category' => $category, 'contrastbg' => 'contrastbg'));?>
        <? endforeach; ?>
    </div>
</div>

<?=$this->render($pdir.'modal.phtml'); ?>
