<? $pdir = '/catalog-manager/partial/'; ?>

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#category" data-toggle="tab">Category</a></li>
        <li><a href="#products" data-toggle="tab">Products</a></li>
    </ul>
 
    <div class="tab-content">

        <div class="active boundary tab-pane" id="category">

            <div class="entity-header hide"><div class="title"></div></div>
            <div class="entity-content">
                <?=$this->partial($pdir.'form/category.phtml', array('category' => $category));?><br/>
            </div>

        </div>

        <div id="products" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>   
                </div>
                <div class="list-items">
                    <? if ($category->hasProducts()) : ?>
                        <? foreach ($category->getProducts() as $product) : ?>
                            <?=$this->partial($pdir.'product.phtml', array('product' => $product));?>
                        <? endforeach; ?>
                    <? endif; ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'import-search',
                        'searchClassName' => 'product',
                        'className'       => 'product',
                        'parentClassName' => 'category',
                        'parentId'        => $category->getCategoryId(),
                        'partialName'     => 'product',
                    ));?>
                </div>
            </div> 
        </div>

    </div>
</div><!--/tabbable-->

<!-- Modal -->
<div class="modal hide fade in" id="modal-box" >
    <div class="modal-header">
        <a class="close" href="#">×</a>
        <h3></h3>
    </div>
    <div style="max-height:300px; overflow:auto;" class="modal-body">
        <p>no results…</p>
    </div>
    <div class="modal-footer">
        Select from the above.
    </div>
</div>  

