


<h3>Products</h3>

<? //$this->paginator = $sessionPaginator;?>
<?//=$this->render('/catalogmanager/partial/entity-list.phtml'); ?>  

<form action='/swmimporter/import-product'>
    <input type="text" name="id"> import a product by id
</form>

<? if(isset($products)) :?>
    
    <? foreach($products as $product) : ?>
    <a href="/catalogmanager/product/<?=$product->getId();?>">"<?=$product;?>"</a><br/>
<? endforeach; ?>
<? endif; ?>
