<? $pdir = '/catalog-manager/partial/'; ?>

<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#product" data-toggle="tab">Product</a></li>
        <li><a href="#options" data-toggle="tab">Options</a></li>
        <li><a href="#specs" data-toggle="tab">Specs</a></li>
    </ul>
 
    <div class="tab-content">

        <div class="active boundary tab-pane" id="product">

            <div class="entity-header hide"><div class="title"></div></div>
            <div class="entity-content">
            <?=$this->partial($pdir.'form/product.phtml', array('product' => $product));?>

            <? if($product->isItem()) :?>
                    <div class="list-wrap">
                        <div class="child-expand list-items-helper">
                            <div><span class="collapse-all ui-icon ui-icon-arrowstop-1-n ui-state-default ui-corner-all"></span></div>
                            <div><span class="expand-all ui-icon ui-icon-arrowstop-1-s ui-state-default ui-corner-all"></span></div>
                            <span class="smallcaps">&nbsp;images</span><br/>
                        </div>   
                        <div class="list-items">
                            <? if (1===2) : //($product->hasUoms()) : ?>
                                <? foreach($product->getUoms() as $productUom) : ?>
                                    <?=$this->partial($pdir.'product-uom.phtml', array('productUom' => $productUom));?>
                                <? endforeach; ?>
                            <? endif; ?>
                        </div>
                        <div class="row list-items-helper">
                            <?=$this->partial($pdir.'add.phtml', array(
                                'function'        => 'import-file',
                                'name'            => 'image',
                                'className'       => 'image',
                                'parentClassName' => 'product',
                                'parentId'        => $product->getProductId(),
                            ));?>
                        </div>
                    </div> 
            
                    <div class="list-wrap">
                        <div class="child-expand list-items-helper">
                            <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                            <div class="expand-all"><i class="icon-arrow-down"></i></div>
                            <span class="smallcaps">&nbsp;uoms</span><br/>
                        </div>   
                        <div class="list-items">
                            <? if ($product->hasUoms()) : ?>
                                <? foreach($product->getUoms() as $productUom) : ?>
                                    <?=$this->partial($pdir.'product-uom.phtml', array('productUom' => $productUom));?>
                                <? endforeach; ?>
                            <? endif; ?>
                        </div>
                        <div class="row list-items-helper">
                            <?=$this->partial($pdir.'add.phtml', array(
                                'function'        => 'add-button',
                                'ClassName'       => 'productUom',
                                'newClassName'    => 'productUom',
                                'parentClassName' => 'product',
                                'parentId'        => $product->getProductId(),
                                'partialName'     => 'product-uom',
                            ));?>
                        </div>
                    </div>
            <? endif; ?>
            </div>

        </div>

        <div id="options" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>   
                </div>
                <div class="list-items">
                    <? if ($product->hasOptions()) : ?>
                        <? foreach ($product->getOptions() as $option) : ?>
                            <?=$this->partial($pdir.'option.phtml', array('option' => $option));?>
                        <? endforeach; ?>
                    <? endif; ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'add-button',
                        'newClassName'    => 'option',
                        'parentClassName' => 'product',
                        'parentId'        => $product->getProductId(),
                        'partialName'     => 'option',
                    ));?>
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'import-search',
                        'searchClassName' => 'option',
                        'className'       => 'option',
                        'parentClassName' => 'product',
                        'parentId'        => $product->getProductId(),
                        'partialName'     => 'option',
                    ));?>
                </div>
            </div> 
        </div>

        <div id="specs" class="tab-pane boundary">
            <div class="list-wrap">
                <div class="child-expand list-items-helper">
                    <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                    <div class="expand-all"><i class="icon-arrow-down"></i></div>   
                </div>
                <div class="list-items">
                    <? if ($product->hasSpecs()) : ?>
                        <? foreach ($product->getSpecs() as $spec) : ?>
                            <?=$this->partial($pdir.'spec.phtml', array('spec' => $spec));?>
                        <? endforeach; ?>
                    <? endif; ?>
                </div>
                <div class="row list-items-helper">
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'add-button',
                        'newClassName'    => 'spec',
                        'parentClassName' => 'product',
                        'parentId'        => $product->getProductId(),
                        'partialName'     => 'spec',
                    ));?>
                    <?=$this->partial($pdir.'add.phtml', array(
                        'function'        => 'import-search',
                        'searchClassName' => 'spec',
                        'className'       => 'spec',
                        'parentClassName' => 'product',
                        'parentId'        => $product->getProductId(),
                        'partialName'     => 'spec',
                    ));?>
                </div>
            </div> 
        </div>
    </div>
</div><!--/tabbable-->

<?=$this->render($pdir.'modal.phtml'); ?>

<div class="hide">

    <div class="tab-pane" id="specs">
        <div class="add-new">
            add a spec
        </div>
    </div>

    <div class="tab-pane" id="parent-choices">
            <? if (count($product->getParentChoices()) > 0) : ?>
                <?=$this->partial($pdir.'entity-list.phtml', array('paginator' => $parentChoicesPaginator)); ?>       
            <? endif; ?>  
    </div>

</div>
