<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link type="text/css" href="/css/smoothness/jquery-ui-1.8.17.custom.css" rel="stylesheet" />
    <link type="text/css" href="/css/contextmenu.css" rel="stylesheet" />
</head>

<style>
    body{ margin:50px; background:#ffffff;}
    form{ margin-bottom:0}
    .smallcaps{font-variant:small-caps; font-size:13px; color:#555555; font-weight:bold}
    .boundary{ 
        margin-bottom:4px; -moz-border-radius: 5px; -webkit-border-radius: 5px; 
        -khtml-border-radius: 5px; border-radius: 5px;
    }
    .add-element{ padding:2px 0 4px 0;}
    .sortable-placeholder{ border:1px solid #000000; background:#bbb; padding: 0 4px 0 4px;}     
    .sort-handle{ cursor:move;}
    .menuitem{ cursor:hand; cursor:pointer;}
    .entity-content{ margin-left:30px;}
    .live-form{ margin: 0 5px 0 5px; opacity:0.7}
    .list-wrap{ min-height:30px; margin-bottom:5px }
    .whitebg { background:#ffffff;}
    .contrastbg{ background: url('/gradient.jpg'); background-repeat: repeat-y;}
    .contrastbg2{ background: url('/gradient2.jpg'); background-repeat: repeat-y;}
    .label{ margin-left:4px; border:1px solid #777777;}
    .entity-header{ height:20px; margin-bottom:2px; margin-top:2px}
    .entity-header span.ui-icon{ margin-top:1px; margin-left:4px;}
    .entity-header div{ float:left; min-width:20px; min-height:20px}
    .entity-header .title{ min-width:300px;}
    .removing{ background:#ff9999;}
    .appearing{ background:#9999ff;}
    .child-expand{ height:20px; margin-bottom:2px; margin-top:2px;}
    .child-expand div{ float:left;}
    .list-items-helper{ opacity: 0.2}
</style>

<body>

    <div class="topbar-wrapper" style="z-index: 5;">
        <div class="topbar" data-dropdown="dropdown">
            <div class="topbar-inner">
               <div class="container">

                    <h3><a href="/catalogmanager">CatalogManager</a></h3>

                    <ul class="nav">
                        <li class="active"><a href="/catalogmanager">Home</a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li><a href="#"></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle">New Product</a>
                            <ul class="dropdown-menu">
                                <li><a href="/catalogmanager/product?new=item" 
                                       title="Single product with an item number">Product (Item)</a>
                                </li>
                                <li><a href="/catalogmanager/product?new=shell" 
                                       title="Group similar products together to be displayed as one">Product Group</a>
                                </li>
                                <li><a href="/catalogmanager/product?new=builder" 
                                       title="Intended for a single product with options that help compose the item number">Product Builder</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="#">Another link</a></li>
                            </ul>
                        </li>
                    </ul>

                    <form id="catalog-search" class="pull-left" action="">
                        <input name="value" class="span3 find-modal" type="text" placeholder="Search">
                    </form>

                    <ul class="nav secondary-nav">
                        <? if(false && $this->zfcUserIdentity()) : ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle">
                                    <? if(isset($session)):?><strong>(<?=count($session);?>)</strong><? endif; ?>
                                    <?=$this->zfcUserIdentity()->getDisplayName();?>
                                </a>
                                <ul class="dropdown-menu">
                                    <li> asdf </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="/user/logout">
                                            Logout
                                        </a>
                                    </li> 
                                </ul>
                            </li>  
                        <? endif; ?>
                    </ul>

                </div>
            </div><!-- /topbar-inner -->
        </div><!-- /topbar -->
    </div>

    <? if (isset($messages)) : ?>
        <? foreach($messages as $this->message) : ?>
            <?=$this->render('/catalogmanager/partial/alert-message.phtml'); ?>
        <? endforeach; ?>
    <? endif; ?>

    <div class="content"> 
        <div class="row"> 
            <div class="span16"> 
                <?php echo $this->raw('content'); ?>
           </div> 
        </div> 
    </div> 

    <!-- Modal -->
    <div class="modal hide fade in" id="modal-box" >
        <div class="modal-header">
            <a class="close" href="#">×</a>
            <h3></h3>
        </div>
        <div style="max-height:300px; overflow:auto;" class="modal-body">
            <p>no results…</p>
        </div>
        <div class="modal-footer">
            Select from the above.
        </div>
    </div>
    
    <ul id="myMenu" class="contextMenu hide"></ul>

</body>
</html>

