</div>
<?
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/ui-lightness.css')
    ->prependStylesheet($this->basePath() . '/css/speck-catalog.css');

$this->headScript()
    ->prependFile($this->basePath() . '/js/speck-catalog-manager.js')
    ->prependFile($this->basePath() . '/js/bootstrap-modal.js', 'text/javascript')
    ->prependFile($this->basePath() . '/js/bootstrap-tab.js', 'text/javascript')
    ->prependFile($this->basePath() . '/js/jquery-ui-1.8.18.js', 'text/javascript')
?>
<ul id="subnav" class="nav nav-pills">
    <li><a href="/admin/catalogmanager">Home</a></li>
    <li><a href="/admin/catalogmanager/products">Products</a></li>
    <li><a href="/admin/catalogmanager/categories">Categories</a></li>
</ul>
<div class="container-fluid">
    <?php echo $this->content; ?>
</div>
<div><? //back to fixed container ?>
