<? $pdir = '/catalogmanager/partial/'; ?>
<div class="boundary whitebg">
    <div class="row">
        <div class="span3 entity-header">
            <div><span class="label sort-handle entity-title">Availability</span></div>
            <div><span class="label important remover hide" title="double click to remove this availability">x</span></div>
        </div>  
        <div class="span6">
            <?=$this->partial($pdir.'form/availability.phtml', array('availability' => $availability));?>
        </div>
    </div>
</div>
