<? $pdir = '/catalogmanager/partial/'; ?>
<? if(isset($availability)) : ?>
    <div class="existing whitebg">
        <div class="row">
            <div class="span2">
                <span class="handle label">Availability</span>
            </div>
            <div class="span6">
                <?=$this->partial($pdir.'form/availability.phtml', array('availability' => $availability));?>
            </div>
        </div>
    </div>
<? else : ?>
    <? if(isset($courtesy)) : ?><div class="add-new whitebg"> <? else : ?><div class="hide add-new whitebg"><? endif; ?>
        <div class="row">
            <div class="span2">
                <span class="handle label success">New Availability</span>
            </div>
            <div class="span6">
                <?=$this->partial($pdir.'form/availability.phtml');?>
            </div>
        </div>
    </div>
<? endif; ?>
