
<? if(isset($availability)) : ?>
    <div class="existing">
        <span class="label">Availability</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('/catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['availability']));?>
            </div>
            <div class="span6">
                <?=$this->partial('catalogmanager/partial/add.phtml', array(
                    'function' => 'import-dropdown', 'name' => 'distributor', 'data' => array('foo' => 'bar',)
                ));?>                                                      
            </div>
        </div>
    </div>
<? else : ?>
    <? if(isset($courtesy)) : ?><div class="add-new"> <? else : ?><div class="hide add-new"><? endif; ?>
        <span class="label success">New Availability</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('/catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['availability']));?>
            </div>
            <div class="span6">
                <?=$this->partial('catalogmanager/partial/add.phtml', array(
                    'function' => 'import-dropdown', 'name' => 'distributor', 'data' => array('foo' => 'bar',)
                ));?>   
            </div>
        </div>
    </div>
<? endif; ?>
