<? if(isset($choice)) : ?>
    <div class="existing">
        <span class="label">Choice</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['choices'][$choice->getChoiceId()]));?> 
            </div>
            <div class="span6">
                <? if ($choice->getProduct()) : ?>
                    <?=$this->partial('/catalogmanager/partial/product.phtml', array(
                        'product' => $choice->getProduct(),
                    ));?>
                <? else : ?>
                    <div class="row">
                        <?=$this->partial('/catalogmanager/partial/add.phtml', array(
                            'function' => 'import-search', 'data'=> array(1=>1), 'name' => 'product'
                        ));?>
                        <?=$this->partial('/catalogmanager/partial/add.phtml', array('function' => 'add-modal-button', 'name' => 'product'));?>
                    </div>
                <? endif; ?>
            </div>
        </div>
    </div>
<? else : ?>
    <? if(isset($courtesy)) : ?> <div class="add-new"> <? else : ?> <div class="add-new hide"> <? endif; ?>
        <span class="label success">New Choice</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['choice']));?>  
            </div>
            <div class="span6">
                <div class="row">
                    <?=$this->partial('/catalogmanager/partial/add.phtml', array(
                        'function' => 'import-search', 'data'=> array(1=>1), 'name' => 'product'
                    ));?>
                    <?=$this->partial('/catalogmanager/partial/add.phtml', array('function' => 'add-modal-button', 'name' => 'product'));?>
                </div>
            </div>
        </div>
    </div>
<? endif; ?>
