<? $pdir = '/catalogmanager/partial/'; ?>
<? if($this->itemUom) : ?>
    <!-- item uom -->
    <div class="existing">
        <span class="handle label">Uom</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial($pdir.'add.phtml', array('function' => 'import-dropdown', 'name'=>'uom', 'data' => $uomData));?>
                <?=$this->partial($pdir.'editform.phtml', array('form' => $forms['item-uom'][$itemUom->getItemUomId()]));?>
            </div>
            <div class="span11">
                <div class="list-wrap">
                    <div class="list-items">
                        <? if (count($this->itemUom->getAvailabilities()) > 0) : ?>
                            <? foreach($this->itemUom->getAvailabilities() as $availability) : ?>
                                <?=$this->partial($pdir.'catalogmanager/partial/availability.phtml', array('availability' => $availability, 'forms' => $forms));?>
                            <? endforeach; ?>
                        <? endif; ?>
                        <?=$this->partial($pdir.'availability.phtml', array('courtesy' => 1, 'forms' => $forms));?>
                    </div>
                    <div class="row">
                        <?=$this->partial($pdir.'availability.phtml', array('forms' => $forms));?>
                        <?=$this->partial($pdir.'add.phtml', array('function' => 'add-button'));?>
                        <?=$this->partial($pdir.'add.phtml', array('function' => 'import-from-search'));?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<? else: ?>
    <!-- new item uom -->
    <? if(isset($courtesy)) : ?><div class="add-new"><? else : ?><div class="hide add-new"><? endif; ?>
        <span class="handle label success">New Uom</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial($pdir.'add.phtml', array('function' => 'import-dropdown', 'name'=>'uom', 'data' => $this->uomData));?>
                <?=$this->partial($pdir.'editform.phtml', array('form' => $forms['blank']['item-uom']));?>
            </div>
            <div class="span11">
                <div class="list-wrap">
                    <div class="list-items">
                        <?=$this->partial($pdir.'availability.phtml', array('courtesy' => 1, 'forms' => $forms));?>
                    </div>
                    <div class="row">
                        <?=$this->partial($pdir.'availability.phtml', array('forms' => $forms));?>
                        <?=$this->partial($pdir.'add.phtml', array('function' => 'add-button', 'name'=>'availability'));?>
                    </div>
                </div>
            </div>
        </div>  
    </div>
<? endif; ?>
