<? if(isset($option)) : ?>
    <!-- option -->
    <div class="existing">
        <span class="label">Option</span>
        <? $parentOptionCount = count($option->getParentProducts()); ?>
        <? if($parentOptionCount > 1) : ?>
            <span class="label warning" title="This option is currently shared amongst <?=$parentOptionCount;?> products.">Shared</span>
        <? endif; ?>   
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['option'][$option->getOptionId()]));?>
            </div>
            <div class="span11 list-wrap">
                <div class="list-items">
                    <? if (count($option->getChoices()) > 0) : ?>
                        <? foreach($option->getChoices() as $choice) : ?>
                            <?=$this->partial('/catalogmanager/partial/choice.phtml', array(
                                'choice' => $choice, 'forms' => $forms,
                            ));?>
                        <? endforeach; ?>
                    <? endif; ?>
                    <?=$this->partial('/catalogmanager/partial/choice.phtml', array('courtesy' => 1, 'forms' => $forms)); ?>
                </div>
                <?=$this->partial('/catalogmanager/partial/add.phtml', array('function' => 'add-button'));?>
                <?=$this->render('/catalogmanager/partial/choice.phtml'); // hidden empty choice?>
            </div>
        </div>
    </div>
<? else: ?>     
    <!-- new option -->
    <? if(isset($courtesy)) : ?> <div class="add-new"> <? else : ?> <div class="hide add-new"> <? endif; ?>
        <span class="label success">New Option</span>
        <div class="row">
            <div class="span5">
                <?=$this->partial('catalogmanager/partial/editform.phtml', array('form' => $forms['blank']['option-radio']));?>
            </div>
            <div class="span11 list-wrap">
                <div class="list-items">
                    <?=$this->partial('/catalogmanager/partial/choice.phtml', array('courtesy' => 1, 'forms' => $forms)); ?>
                </div>
                <?=$this->partial('/catalogmanager/partial/add.phtml', array('function' => 'add-button'));?>
                <?=$this->partial('/catalogmanager/partial/choice.phtml', array('forms' => $forms)); // hidden empty choice?>
            </div>
        </div>
    </div>
<? endif; ?>
