 <div id="product-<?=(isset($itemUom)&& $itemUom->getItemUomId()?$itemUom->getItemUomId():'new');?>" class="live-form">
    <div class="row">
        <div class="span5">
            <div class="row">
                <div class="span3">
                    Distributor
                    <select name="distributor" class="span3">
                        <option>asdf</option>
                    </select>    
                </div>

                <div class="span2">
                    Cost<br/>
                    <input name="cost" class="span2" type="text"/>
                </div>
            </div>
        </div> 
    </div> 
</div>  
