<? $pdir = '/catalogmanager/partial/'; ?>
<form id="availability-<?=$availability->getAvailabilityId();?>">

    <input type="hidden" name="availability_id" value="<?=$availability->getAvailabilityId();?>"/>
    <input type="hidden" name="parent_product_uom_id" value="<?=$availability->getParentProductUomId();?>"/>
    
    <div id="availability-<?=$availability->getAvailabilityId();?>" class="live-form">
        <div class="row">
            <div class="span5">
                <div class="row">
                    <div class="span3">
                        Distributor


                        <select name="distributor_company_id" class="span3">
                            <?=$this->partial($pdir.'form/select-options.phtml', array(
                                'data' => $availability->getCompanies(),
                                'getIdMethod' => 'getCompanyId',
                                'selectedId'  => $availability->getDistributorCompanyId(),
                                'getNameMethod' => 'getName',
                            ));?>
                        </select>

                    </div>

                    <div class="span2">
                        Cost<br/>
                        <input name="cost" class="span2" value="<?=$availability->getCost();?>" type="text"/>
                    </div>
                </div>
            </div> 
        </div> 
    </div>
</form>                                                                              
