<form id="choice-<?=$choice->getChoiceId();?>">
    <div id="choice-<?=$choice->getChoiceId();?>" class="live-form row quarter-pad">
            <div class="span3">
                <input type="hidden" name="choice_id" value="<?=$choice->getChoiceId();?>"/>
                <input type="hidden" name="product_id" value="<?=$choice->getProductId();?>"/>
                <input type="hidden" name="parent_option_id" value="<?=$choice->getParentOptionId();?>"/>
                Override Name<br/>
                <input name="override_name" class="span3" type="text" value="<?=(isset($choice)?$choice->getOverrideName():'');?>"/>
            </div>  
            <div class="span2">
                Price Discount<br/>
                <input name="priceDiscount" class="span2" type="text" value="0"/>
            </div>
            <div class="span2">
                Price Increase<br/>
                <input name="priceIncrease" class="span2" type="text" value="0"/>
            </div>
    </div>
</form>  
