<div id="itemUom-<?=(isset($itemUom)&& $itemUom->getItemUomId()?'':'');?>" class="row quarter-pad live-form">
        <div class="span4">
            <div class="row">
                <div class="span2">
                    Uom<br/>
                    <select class="span2">
                        <option>asdf</option>
                    </select>
                </div>
                <div class="span1">
                    Qty<br/>
                    <input class="span1" type="text"/>
                </div>  
            </div>
            <div class="row">
                <div class="span2">
                    Retail<br/>
                    <input class="span2" type="text"/>
                </div>
                <div class="span2">
                    Price<br/>
                    <input class="span2" type="text"/>
                </div>
            </div>
        </div> 
</div>
