<? $pdir = '/catalogmanager/partial/'; ?>
<form id="option-<?=$option->getOptionId();?>" class="live-form collapse">
    
    <input type="hidden" name="option_id" value="<?=$option->getOptionId();?>"/>

    <div class="row offset0">
       
        <div class="span2">
            <span class="smallcaps">list type</span><br/>
            <select name="list_type" class="span2">
                <?=$this->partial($pdir.'form/select-options.phtml', array(
                    'data' => $option->getListTypes(),
                    'selectedId'  => $option->getListType(),
                ));?>
            </select> 
        </div>
        
        <div class="span3">
            <span class="smallcaps">name</span><br/>
            <input name="name" class="span3" type="text" value="<?=$option->getName();?>"/>
        </div>
          
        <div class="span3">
            <span class="smallcaps">instruction</span><br/>
            <input name="instruction" class="span3" type="text" value="<?=$option->getInstruction();?>"/>
        </div>
        </form>

    </div>

</form><br/>  
