<form id="productUom-<?=$productUom->getProductUomId();?>" class="live-form">
    
    <input type="hidden" name="product_uom_id" value="<?=$productUom->getProductUomId();?>"/>
    <input type="hidden" name="parent_product_id" value="<?=$productUom->getParentProductId();?>"/>
    
    <div class="row quarter-pad">
        <div class="span4">
            <div class="row">
                <div class="span2">
                    <span class="smallcaps">uom</span><br/>
                    <select class="span2">
                        <option>asdf</option>
                    </select>
                </div>
                <div class="span1">
                    <span class="smallcaps">qty</span><br/>
                    <input class="span1" type="text" name="quantity" value="<?=$productUom->getQuantity();?>"/>
                </div>  
            </div>
            <div class="row">
                <div class="span2">
                    <span class="smallcaps">retail</span><br/>
                    <input class="span2" type="text" name="retail" value="<?=$productUom->getRetail();?>"/>
                </div>
                <div class="span2">
                    <span class="smallcaps">price</span><br/>
                    <input class="span2" type="text" name="price" value="<?=$productUom->getPrice();?>"/>
                </div>
            </div>
        </div> 
    </div>

</form><br/>
