<?
$depth = isset($depth) ? $depth : 0;
$products = isset($products) ? $products : array();

function renderCategories($categories, $depth){
    foreach ($categories as $i => $category) {
        echo '<div id="' . $category->getCategoryId() . '" class="tree-cat">';
        echo '<div class="tree-cat-title title"><b>:C: </b>'. $category->getName() . '</div>';
            echo '<div class="tree-cat-cats cat-sort">';
            if ($category->has('categories') ) {
                renderCategories($category->getCategories(), $depth+1);
            }
            echo '</div>';
            echo '<div class="tree-cat-products product-sort">';
            echo '</div>';
        echo '</div>';
    }
}

function renderProducts($products, $depth){
    foreach ($products as $i => $product) {
        echo '<div id="' . $product->getProductId() . '" class="tree-product">'. $product->getName() . '</div>';
    }
}

renderCategories($categories, $depth);
renderProducts($products, $depth);
?>
