<?php
    $formHelper = $this->speckCatalogForm($document, 'document');
?>

<div class="boundary contrastbg" id="">
    <div class="entity-header">
        <div class="remover left"><div class="hide"><span class="icon-remove" title="double click to remove"></span></div></div>
        <div class="left"><i class="icon-file"></i></div>
        <div class="title sort-handle left">&nbsp; <?=$document;?></div>
    </div>
    <div class="entity-content initialcol">
        <?= $formHelper->renderForm(); ?>
    </div>
</div>
