<form class="search">
    <? foreach ($fields as $key => $val) : ?>
        <? if(is_array($val)) : ?>
            <? foreach($val as $key2 => $val2) : ?>
                <input type="hidden" name="<?=$key;?>[<?=$key2;?>]" value="<?=$val2;?>" />
            <? endforeach;?>
        <? else: ?>
            <input type="hidden" name="<?=$key;?>" value="<?=$val;?>" />
        <? endif; ?>
    <? endforeach; ?>
    <input type="text" name="query"></input>
</form>

<? if(count($models)) : ?>
    <form class="found">
        <? foreach ($fields as $key => $val) : ?>
            <? if(is_array($val)) : ?>
                <? foreach($val as $key2 => $val2) : ?>
                    <input type="hidden" name="<?=$key;?>[<?=$key2;?>]" value="<?=$val2;?>" />
                <? endforeach;?>
            <? else: ?>
                <input type="hidden" name="<?=$key;?>" value="<?=$val;?>" />
            <? endif; ?>
        <? endforeach; ?>
        <? $n=0; ?>
        <? foreach($models as $model) : ?>
            <? $n++; ?>
            <? $fields = $this->speckCatalogForm($model, 'product')->getKeyFields();?>
            <? foreach($fields as $key => $val): ?>
                <input type="hidden" name="<?=$key;?>[<?=$n;?>]" value="<?=$val;?>" />
            <? endforeach;?>
            <input type="checkbox" name="check[<?=$n;?>]" value="1">&nbsp;<?=$model;?></input><br/>
        <? endforeach; ?>
        <input type="submit">
    </form>
<? endif; ?>
