<?php
    $parentProductKeyFields = $this->SpeckCatalogForm($productUom->getParent(), 'product')->getKeyFields();

    $formHelper = $this->speckCatalogForm($productUom, 'product_uom');
    $productUomKeyFields = $formHelper->getKeyFields();
?>

<div class="existing contrastbg boundary shadow" id="">
<div class="entity-header">
    <div class="collapser left"><i class="icon-chevron-down"></i></div>
    <div class="title collapser left">&nbsp;<?=$productUom;?></div>
    <div class="remover right">
        <?= $this->speckCatalogAdderHelper()->removeChild('product', $parentProductKeyFields, 'product_uom', $productUomKeyFields); ?>
    </div>
</div>
    <div class="entity-content">
        <div class="row">
            <div class="span5">
                <?= $formHelper->renderForm(); ?>
            </div>
            <div class="span6">
                <div class="list-wrap">
                    <div class="child-expand list-items-helper">
                        <div class="collapse-all"><i class="icon-arrow-up"></i></div>
                        <div class="expand-all"><i class="icon-arrow-down"></i></div>
                        <span class="smallcaps">&nbsp;availabilities</span><br/>
                    </div>
                    <div class="list-items">
                        <?=$this->speckCatalogRenderChildren('availability', $productUom->getAvailabilities());?>
                    </div>
                    <div class="row list-items-helper">
                        <?=$this->speckCatalogAdderHelper()->addNew('availability', 'product_uom', $productUomKeyFields); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
