<div class="boundary contrastbg2 shadow">
    <div class="entity-header">
        <div>
            <div class="left"><i class="icon-tag"></i></div>
            <div class="left"><a class="icon-pencil" href="/admin/catalogmanager/product/<?=$product->getProductId();?>" title="edit this"></a></div>
            &nbsp; <?=$product; ?>
            <?=$product->getItemNumber(); ?>
            <? if($product->has('uoms')) : ?>
                <? foreach($product->getUoms() as $uom) : ?>(<?=$uom;?>)<? endforeach;?>
            <? endif; ?>
        </div>
    </div>
</div>
