<?
 // this is a partial used by a viewhelper
?>


<style>
/* Sidenav for Docs
-------------------------------------------------- */

.bs-docs-sidenav {
  width: 150px;
  margin: 30px 0 0 0;
  padding: 0;
  background-color: #fff;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
  -webkit-box-shadow: 0 1px 4px rgba(0,0,0,.065);
     -moz-box-shadow: 0 1px 4px rgba(0,0,0,.065);
          box-shadow: 0 1px 4px rgba(0,0,0,.065);
}
.bs-docs-sidenav > li > a {
  display: block;
  width: 150px \9;
  margin: 0 0 -1px;
  padding: 8px 14px;
  border: 1px solid #e5e5e5;
}
.bs-docs-sidenav > li:first-child > a {
  -webkit-border-radius: 6px 6px 0 0;
     -moz-border-radius: 6px 6px 0 0;
          border-radius: 6px 6px 0 0;
}
.bs-docs-sidenav > li:last-child > a {
  -webkit-border-radius: 0 0 6px 6px;
     -moz-border-radius: 0 0 6px 6px;
          border-radius: 0 0 6px 6px;
}
.bs-docs-sidenav > .active > a {
  position: relative;
  z-index: 2;
  padding: 9px 15px;
  border: 0;
  text-shadow: 0 1px 0 rgba(0,0,0,.15);
  -webkit-box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
     -moz-box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
          box-shadow: inset 1px 0 0 rgba(0,0,0,.1), inset -1px 0 0 rgba(0,0,0,.1);
}
/* Chevrons */
.bs-docs-sidenav .icon-chevron-right {
  float: right;
  margin-top: 2px;
  margin-right: -6px;
  opacity: .25;
}
.bs-docs-sidenav > li > a:hover {
  background-color: #f5f5f5;
}
.bs-docs-sidenav a:hover .icon-chevron-right {
  opacity: .5;
}
.bs-docs-sidenav .active .icon-chevron-right,
.bs-docs-sidenav .active a:hover .icon-chevron-right {
  background-image: url(../img/glyphicons-halflings-white.png);
  opacity: 1;
}
.bs-docs-sidenav.affix {
  top: 40px;
}
.bs-docs-sidenav.affix-bottom {
  position: absolute;
  top: auto;
  bottom: 270px;
}


/* Responsive
-------------------------------------------------- */

/* Desktop large
------------------------- */
@media (min-width: 1200px) {
  .bs-docs-container {
    max-width: 970px;
  }
  .bs-docs-sidenav {
    width: 178px;
  }
  .bs-docs-sidenav > li > a {
    width: 178px \9; /* Override the previous IE8-9 hack */
  }
}

/* Desktop
------------------------- */
@media (max-width: 980px) {
  .bs-docs-sidenav {
    top: 0;
    margin-top: 30px;
    margin-right: 0;
  }
}

@media (max-width: 979px) and (min-width: 768px) {
  .bs-docs-sidenav {
    width: 120px;
  }
  .bs-docs-sidenav > li > a {
    width: 120px \9; /* Override the previous IE8-9 hack */
  }
}

/* Tablet
------------------------- */
@media (max-width: 767px) {

  /* Sidenav */
  .bs-docs-sidenav {
    width: auto;
    margin-bottom: 20px;
  }
  .bs-docs-sidenav.affix {
    position: static;
    width: auto;
    top: 0;
  }
}

</style>

<?
    $buttons = array(
        array(
            'action' => 'index',
            'title' => 'Overview',
            'url'  => '/catalogmanager',
        ),
        array(
            'action' => 'products',
            'title' => 'Products',
            'url'  => '/catalogmanager/products',
        ),
        array(
            'action' => 'categories',
            'title' => 'Categories',
            'url'  => '/catalogmanager/categories',
        ),
    );
?>
<div class="span2 bs-docs-sidebar">
    <ul class="nav nav-list bs-docs-sidenav affix">
        <? foreach($buttons as $button) : ?>
            <? $class = $action === $button['action'] ? 'class="active" ' : ''; ?>
            <li <?=$class;?>><a href="<?=$button['url'];?>"><i class="icon-chevron-right"></i><?=$button['title'];?></a></li>
        <? endforeach; ?>
    </ul>
</div>
