<?php
    $parentProductKeyFields = $this->speckCatalogForm($spec->getParent(), 'product')->getKeyFields();
    $formHelper = $this->speckCatalogForm($spec, 'spec');
    $keyFields = $formHelper->getKeyFields();
?>
<div class="boundary contrastbg">
    <div class="entity-header">
        <div class="title sort-handle left">&nbsp; <?=$spec;?></div>
        <div class="remover right">
            <?= $this->speckCatalogAdderHelper()->removeChild('product', $parentProductKeyFields, 'spec', $keyFields); ?>
        </div>
    </div>
    <div class="entity-content">
        <?= $formHelper->renderForm(); ?>
    </div>
</div>
